### ISSUE TITLE
Actix HTTP Responses can be more idiomatic

### ISSUE THREAD

**Issue by chaosteil** [LukeMathWalker/zero-to-production#100]
There is this line that was added to the subscriptions.go response but can be much nicer:

https://github.com/LukeMathWalker/zero-to-production/blob/8584ce6891403bff6c5ab292b32b25287b2a90e4/src/routes/subscriptions.rs#L23

```rust
use actix_web::{web, HttpResponse, Result}
/*
...
*/
pub async fn subscribe(form: web::Form<FormData>, pool: web::Data<PgPool>) -> Result<HttpResponse> {
    insert_subscriber(&pool, &form)
        .await
        .map_err(actix_web::error::ErrorInternalServerError)?;
    Ok(HttpResponse::Ok().finish())
}
```

I had problems with newer versions to compile it at all, but this should be both backwards and forwards compatible.

**Comment by LukeMathWalker** [comment]
You are indeed right - that's more idiomatic. And we land on something along those lines in Chapter 8, when we discuss error handling.
There a lot of considerations to be made on how to use `actix_web::Error` and they would be premature in the early chapters.

The other point you raised is valid of course: `actix_web` latest beta are iterating on their error management story which breaks some of the code in the book (we currently pin `beta.5`).
I am waiting for the next release (which should contain the bulk of the changes) before updating all chapters to compile on latest.

**Comment by LukeMathWalker** [comment]
Solved in the release going out tomorrow 😁
