### ISSUE TITLE
TryFrom or TryInto?

### ISSUE THREAD

**Issue by skovmand** [LukeMathWalker/zero-to-production#101]
I'm in doubt what the best/ideomatic way of writing this is and would just raise the question here (BTW: I wish there was a chat room for the book readers.)

On page 154, I have implemented `TryInto<NewSubscriber> for FormData`:

```rust
impl TryInto<NewSubscriber> for FormData {
    type Error = String;

    fn try_into(self) -> Result<NewSubscriber, Self::Error> {
        let email = SubscriberEmail::parse(self.email)?;
        let name = SubscriberName::parse(self.name)?;

        Ok(NewSubscriber { email, name })
    }
}

// ...

pub async fn subscribe(form: web::Form<FormData>, pool: web::Data<PgPool>) -> Result<HttpResponse, HttpResponse> {
    let new_subscriber = form.0.try_into().map_err(|_| HttpResponse::BadRequest().finish())?;
    // ...
}
```

And I think it's really cool to use `TryInto` this way. I appriciate to learn these standard way of dealing with conversions!

However, then I read a bit about `From` and `Into` in [Rust By Example](https://doc.rust-lang.org/stable/rust-by-example/conversion/from_into.html) and found that implementing `From` would also work, and even for both `form.0.try_into()` and `NewSubscriber::try_from(form.0)` because `Into` calls `From`.

So my question: Would the intent be clearer implementing `TryFrom` instead?:

```rust
impl TryFrom<FormData> for NewSubscriber {
    type Error = String;

    fn try_from(form: FormData) -> Result<NewSubscriber, Self::Error> {
         let email = SubscriberEmail::parse(form.email)?;
         let name = SubscriberName::parse(form.name)?;
 
         Ok(NewSubscriber { email, name })
    }
}

// ...

pub async fn subscribe(form: web::Form<FormData>, pool: web::Data<PgPool>) -> Result<HttpResponse, HttpResponse> {
    // I find this more readable, since the intent is very clear
    let new_subscriber = NewSubscriber::try_from(form.0).map_err(|_| HttpResponse::BadRequest().finish())?;

    // And try_into() still works (although not at the same time as try_from above due to move semantics)
    let new_subscriber = form.0.try_into().map_err(|_| HttpResponse::BadRequest().finish())?;

    // ...
}
```

So, I just wanted to leave this thought/question here. For what it's worth.
Thanks for your book, I have learned a lot from it already.

(Edit: Added syntax highlighting)

**Comment by eeff** [comment]
@skovmand Implementing `TryFrom` and `TryInto` should work the same in this case, but one benefit of implementing `TryFrom`
is that you automatically get an implementation for `TryInto` for free.
There is a blanket implementation from the standard library.
``` rust
// https://doc.rust-lang.org/core/convert/trait.TryInto.html
// TryFrom implies TryInto
impl<T, U> TryInto<U> for T
where
    U: TryFrom<T>,
{ ... }
```

For those who are interested, have a read at this [blog post](https://ricardomartins.cc/2016/08/03/convenient_and_idiomatic_conversions_in_rust).

I do follow the [an-introduction-to-property-based-testing-in-rust](https://www.lpalmieri.com/posts/an-introduction-to-property-based-testing-in-rust/#payload-validation), but I prefer to implement  `TryFrom`.

**Comment by skovmand** [comment]
Very nice blog post you referred to. Thanks 👍

**Comment by LukeMathWalker** [comment]
I went for `TryInto` because, down the line, we will be splitting the project into multiple crates - the API-related bits and the domain-related bits will end up in separate crates within the same workspace.  
An important constraint that we will enforce is inversion of control - the domain crate will NOT depend on the API crate.

Before Rust 1.41.x, it would have not been possible (with such a constraint in place) to implement `TryFrom` - the orphan rule would have prevented it. But the coherence rule has been relaxed, therefore it would probably be better to go straight for `TryFrom` there.

I'll update the book at a certain point to reflect it 😁

**Comment by skovmand** [comment]
@LukeMathWalker Thanks for your answer 👍

**Comment by LukeMathWalker** [comment]
This has been fixed - it will go out with the next book release 😁
