### ISSUE TITLE
tracing::instrument name conflict

### ISSUE THREAD

**Issue by vaassi** [LukeMathWalker/zero-to-production#102]
Dear Luca, I found some little issue when checking logs output in subscriptions.rs file

```
#[tracing::instrument(
    name = "Adding a new subscriber.",
    skip(form, pool),
    fields(
        email = %form.email,
        name = %form.name
    )
)]
pub async fn subscribe(
    form: web::Form<FormData>,
    pool: web::Data<PgPool>,
) -> Result<HttpResponse, HttpResponse> {
```

**name = %form.name** -> this param is conflicting with tracing name param and not showing in final logs, if I change it to different name, f.e. **username = %form.name**, it begins to show.

Thanks for this amazing book!

**Comment by LukeMathWalker** [comment]
Classic example of fixing a bug in one place (`tracing-bunyan-formatter`) just to create a different bug in another place 😅 
I'll have to rename the parameter - something to pick up before the next release.

**Comment by LukeMathWalker** [comment]
Fixed, it will go out with the next release 🚀
