### ISSUE TITLE
Implementing actix-cors

### ISSUE THREAD

**Issue by ianckc** [LukeMathWalker/zero-to-production#103]
I've been trying to implement actix-cors on top of the basic health check but I get the error

`the trait 'Transform<actix_web::app_service::AppRouting, ServiceRequest>' is not implemented for 'Cors'`

Has anyone implemented Cors on top of the code from the book?

My dependencies are

```
[dependencies]
actix-web = "4.0.0-beta.3"
reqwest = "0.11"
actix-cors = "0.5.4"

[dev-dependencies]
actix-rt = "2"
tokio = { version = "1", features = ["macros"] }
```

Then lib.rs contains

```
use actix_cors::Cors;
use actix_web::dev::Server;
use actix_web::{web, App, HttpResponse, HttpServer};

async fn health_check() -> HttpResponse {
    HttpResponse::Ok().finish()
}

pub fn run() -> Result<Server, std::io::Error> {
    let server = HttpServer::new(|| {
        let cors = Cors::permissive();
        App::new()
            .wrap(cors)
            .route("/health_check", web::get().to(health_check))
    })
    .bind("127.0.0.1:8976")?
    .run();
    Ok(server)
}
```

Thanks

**Comment by LukeMathWalker** [comment]
Version `0.5.4` of `actix-cors` depends on version `3.x.x` of `actix-web` - that should be the root cause of the error you are seeing.
Try to update to `0.6.0-beta.1`!

**Comment by ianckc** [comment]
That is working. Something for me to work on, using `cargo tree` to debug this sort of thing.

Thanks so much.
