### ISSUE TITLE
Cannot assign requested address while running from docker

### ISSUE THREAD

**Issue by vinay10949** [LukeMathWalker/zero-to-production#113]
Postgress Docker 
  # Launch postgres using Docker
  sudo docker run \
      -e POSTGRES_USER=${DB_USER} \
      -e POSTGRES_PASSWORD=${DB_PASSWORD} \
      -e POSTGRES_DB=${DB_NAME} \
      -p "${DB_PORT}":5432 \
      -d \
      --name "postgres_$(date '+%s')" \
      --net=bridge  \
      postgres -N 1000

zero2prod container
 sudo docker run -p 8000:8000 --net=bridge zero2prod

Connection String postgres://postgres:password@localhost:5432/newsletter
thread 'main' panicked at 'Failed to connect to Postgres.: Io(Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })', src/main.rs:22:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by cgubbin** [comment]
I am having the same issue on macOS.

**Comment by abhyuditjain** [comment]
I am having the same issue on Windows 10.

**Comment by LukeMathWalker** [comment]
I think you are running into the issue described here: https://docs.docker.com/network/bridge/#enable-forwarding-from-docker-containers-to-the-outside-world

The best way forward is to create a user-defined network, as described [here](https://www.tutorialworks.com/container-networking/).
You should then be able to connect to Postgres using `postgres_1632760402` as hostname (the name of the Docker container running Postgres) instead of `localhost`.

**Comment by rGustave07** [comment]
@LukeMathWalker

Hello :)

So I was having the same problem as the original poster, so I created a user-defined network and connected the two containers to it. Now I'm not getting the 'cannot assign requested address' error but another error entirely:

PgDatabaseError "relation 'subscriptions' does not exist". 

There is no wait time after I send the curl POST it's instant. Any idea how I can resolve this?

**Comment by LukeMathWalker** [comment]
You need to migrate your database!

**Comment by rGustave07** [comment]
> You need to migrate your database!

This is right! So it seems like I had a local instance of Postgres running on the same port so I had to map my container port to something else. Otherwise my other Postgres instance got the migration and the container doesn't.
