### ISSUE TITLE
Running migrations on DO's database 

### ISSUE THREAD

**Issue by Tevinthuku** [LukeMathWalker/zero-to-production#116]
Whenever I try to run the migrations on Digital Ocean's database locally, I get this error

![image](https://user-images.githubusercontent.com/12128153/132122382-04a5b52b-3447-4f22-b528-17c016b06529.png)

If I disable trusted sources 
![image](https://user-images.githubusercontent.com/12128153/132122328-3418e97e-c498-4fb6-b054-6d905e0ea2e8.png)

the migrations run as expected.

![image](https://user-images.githubusercontent.com/12128153/132122313-a3bee7b2-1ee8-4fe5-96ef-7f829970c2ce.png)

I always enable trusted sources again after the migration runs.

Is there a way to fix this without having to toggle the setting, Thanks!

**Comment by LukeMathWalker** [comment]
This "Trusted Sources" business is new 😁 Quite a nice feature though, providing network isolation by default.

I think you have two options:
- Do what you just did, disable it temporarily;
- Run SQL migrations before the app starts.

**Comment by Tevinthuku** [comment]
Okay, thanks a lot. I really enjoy reading the book!
