### ISSUE TITLE
Page 216: subscribe_returns_a_200_for_valid_form_data

### ISSUE THREAD

**Issue by bellemere** [LukeMathWalker/zero-to-production#120]
The document:
```Rust
#[actix_rt:: test]
async fn subscribe_returns_a_200_for_valid_form_data() {
    // Arrange
    let app = spawn_app().await;
    let body = "name=le%20guin&email=ursula_le_guin%40gmail.com";
    // Act
    let response = app.post_subscriptions(body.into()).await;
    // Assert
    assert_eq!(200, response.status().as_u16());
}
```
should fail because the email server isn't mocked.
The code in your github is right.

Still, thanks a lot for your contribution.

**Comment by bellemere** [comment]
Also on page 229, the parameter of `insert_subscriber` should be pool instead of transaction because transaction is discussed in next section.

**Comment by LukeMathWalker** [comment]
Both have been fixed - the revised version will be released on Jan 4th. Thanks for reporting!
