### ISSUE TITLE
Page 20: Actix http - no `new_connector` in `connect`

### ISSUE THREAD

**Issue by z4f1r0v** [LukeMathWalker/zero-to-production#121]
I get an error when trying to go through the very first code piece in the book. Here is how my project is setup and the error that I'm getting.

Cargo.toml:
```
[package]
name = "zero2prod"
version = "0.1.0"
authors = ["auth <author@me.com"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "=4.0.0-beta.9"
#actix-http = "=3.0.0-beta.10"

[dev-dependencies]
actix-rt = "1"
reqwest = "0.11"
tokio = { version = "1", features = ["macros"] }
```

Error:
```
error[E0432]: unresolved imports `actix_tls::connect::new_connector`, `actix_tls::connect::Connect`
  --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.10/src/client/connector.rs:17:5
   |
17 |     new_connector, Connect as TcpConnect, ConnectError as TcpConnectError,
   |     ^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^ no `Connect` in `connect`
   |     |
   |     no `new_connector` in `connect`
   |
help: a similar name exists in the module
   |
17 |     connector, Connect as TcpConnect, ConnectError as TcpConnectError,
   |     ~~~~~~~~~
help: a similar name exists in the module
   |
17 |     new_connector, Connector as TcpConnect, ConnectError as TcpConnectError,
   |                    ~~~~~~~~~

error[E0432]: unresolved import `actix_tls::connect::Connect`
  --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.10/src/client/mod.rs:14:5
   |
14 |     Connect as TcpConnect, ConnectError as TcpConnectError, Connection as TcpConnection,
   |     -------^^^^^^^^^^^^^^
   |     |
   |     no `Connect` in `connect`
   |     help: a similar name exists in the module: `Connector`

error[E0282]: type annotations needed
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.10/src/client/connector.rs:267:28
    |
267 |     pub fn finish(self) -> ConnectorService<S, Io> {
    |                            ^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `Io`

error[E0282]: type annotations needed
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.10/src/client/connector.rs:531:13
    |
531 | impl<S, Io> Service<Connect> for TcpConnectorInnerService<S>
    |             ^^^^^^^^^^^^^^^^ cannot infer type for type parameter `Io`

error[E0282]: type annotations needed
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.10/src/client/connector.rs:546:8
    |
546 |     fn call(&self, req: Connect) -> Self::Future {
    |        ^^^^ cannot infer type for type parameter `Io`

error[E0282]: type annotations needed
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.10/src/client/connector.rs:544:5
    |
544 |     actix_service::forward_ready!(service);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `Io`
    |
    = note: this error originates in the macro `actix_service::forward_ready` (in Nightly builds, run with -Z macro-backtrace for more info)
```

If I try to move to non-beta versions of the `actix` dependencies (and nothing else), I get `actix panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'`. So I'm stuck and cannot proceed. Please advise!

**Comment by LukeMathWalker** [comment]
It seems like the newest beta of actix-tls is not compatible with the beta of actix-web we are using in the book.
Can you try using the latest actix-web beta - `4.0.0-beta.14`?

**Comment by TuhinNair** [comment]
Keep in mind this is my first time working with the rust ecosystem, so some changes may be extraneous. I had the same compilation errors after adding `v0.4.0-beta.12` of the `tracing-actix-web` crate to my project. That version of the `tracing-actix-web` crate pinned the `actix-web` dependency to `4.0.0-beta.10` but I fixed it by using `cargo tree` and checking what versions of dependencies play well with each other.

The final versions of the crates I used (Showing only the ones I changed):
`
[dependencies]
actix-http = "=3.0.0-beta.15"
actix-web = "=4.0.0-beta.14"
tracing-actix-web = "=0.5.0-beta.5"
`
The version of the book I'm reading (with 10 chapters completed) recommends `v0.4.0-beta.12` of the `tracing-actix-web` crate but I had to use a higher minor version. Not sure of the ramifications but the code compiles and all my tests pass. 

For your use my only recommendation is to use `actix-http v3.0.0-beta.15` alongside `actix-web v4.0.0-beta.14`.

**Comment by z4f1r0v** [comment]
@LukeMathWalker @TuhinNair thank you for your suggestions. Unfortunately no combination of the two dependencies you suggested leads me to pass `actix panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime` successfully. Could I possibly bother you for a working Gist or a dummy repo that compiles for you?

**Comment by z4f1r0v** [comment]
To tell the truth - all this meddling with versions is really off-putting for a Rust newbie like me. I thought that the point of actix is that it is stable and quite adopted by the community. Coming from Scala where people love to hate on the lack of binary compatibility between minor versions of the Akka library, I've only had this situation on the in my career. So year, I'd appreciate your help :)

**Comment by LukeMathWalker** [comment]
It's easier to advise if you share your repo 😁 
The current situation of instability is indeed unfortunate. Looking forward to `actix-web` v4 coming out proper.

**Comment by devzx** [comment]
I was having the same issue at section "3.3.1 Wiring Up actix-web" , updating my dependencies to those suggested by @TuhinNair got it working.

**Comment by TuhinNair** [comment]
@z4f1r0v Guessing here but you're problem could either be:
1. You've explicitly specified `tokio` as a dependency and it's a pre V1 version. In that case using something like `tokio = "1.14"` should do the trick. That being said, I haven't had to explitly specify tokio (expect as a dev-dependeny but that should be unrelated here) as the crates used in the book use tokio internally.

2. You're using a dependency that pins tokio to pre V1 which in turn is incompatible with crates that require >= V1 (I'm not sure how cargo actually resolves situations like this). From my current progress of the book, there are 3 dependencies that depend on tokio. They all have `tokio v1.14` as a dependency.
Showing the ones with tokio as an internal dependency:
```
[dependencies]
actix-http = "=3.0.0-beta.15"
actix-web = "=4.0.0-beta.14"

[dependencies.sqlx]
version = "0.5.7"
default-features = false
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]
```

**Comment by z4f1r0v** [comment]
Thank you, gentlemen, for your time. Maybe it wasn't apparent from my initial post - apologies for the confusion - it is the first test `health_check.rs` that fails to pass. The app it self runs successfully and can be reached (e.g via cURL). 
@LukeMathWalker, as requested - https://github.com/z4f1r0v/zero2prod. I hope we can find the solution :)

**Comment by TuhinNair** [comment]
@z4f1r0v I had assumed you meant running the app and not the tests. In this case your fix is straightforward. The current version of `actix-rt` in your dev-dependencies depends on an older version of tokio (`v0.2.25`) which is incompatible with the version of actix-* we're using. Change your dependencies to the following and you should be ok:
```
[dev-dependencies]
actix-rt = "2.5.0"
```

**Comment by z4f1r0v** [comment]
@TuhinNair boyakasha! Case closed. Happy holidays 🎄

**Comment by skippednote** [comment]
I was able to solve the problem by upgrading to the latest betas and without adding a dev dependency.
```
[dependencies]
actix-web = "4.0.0-beta.15"
actix-http = "=3.0.0-beta.16"
```
