### ISSUE TITLE
Compiling sqlx-macros v0.5.9 fails on Mac M1

### ISSUE THREAD

**Issue by z4f1r0v** [LukeMathWalker/zero-to-production#126]
Hello,

I just got the said laptop and am having a problem compiling the `sqlx-macros` crate. 

For the curious, I'm getting
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" ...
  = note: ld: framework not found CoreFoundation
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `sqlx-macros` due to previous error
```

My biggest lead was [this](https://github.com/rusqlite/rusqlite/issues/934) somewhat-related, yet still unanswered thread.

I know this is not a problem with the project per se, but I thought that it brings visibility to the fact that the community is in a transition period.

All ideas/suggestions are welcome.

**Comment by LukeMathWalker** [comment]
I don't have an M1 (yet!) so I am afraid I can't help debugging the issue, but hopefully someone else in the community can jump in 💪

Have you opened an issue on sqlx's repository?

**Comment by z4f1r0v** [comment]
Thanks @LukeMathWalker - I will do so now.
