### ISSUE TITLE
Use mold linker

### ISSUE THREAD

**Issue by pickfire** [LukeMathWalker/zero-to-production#127]
Mold linker can probably result in linking faster than llvm https://www.lpalmieri.com/posts/session-based-authentication-in-rust/#2-1-faster-linking

https://github.com/rui314/mold#how-to-use

**Comment by LukeMathWalker** [comment]
`mold` is quite new and it must be compiled from source at the moment - it's mentioned in the footnotes of the relevant section, but I don't think it should be recommended as the go-to option just yet.

**Comment by pickfire** [comment]
It's also mentioned in https://fasterthanli.me/articles/why-is-my-rust-build-so-slow and for me (arch linux), it's available in the package manager on community repo.
