### ISSUE TITLE
Typo in Chapter 9.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#128]
- In [the 2nd code box](https://www.lpalmieri.com/posts/naive-newsletter-delivery/#do-not-spam-unconfirmed-subscribers) in Do Not Spam Unconfirmed Subscribers has `//! tests/api/newsletters.rs` as the file name, but this should be `//! tests/api/newsletter.rs`.

- In the first code box in [All Confirmed Subscribers Receive New Issues](https://www.lpalmieri.com/posts/naive-newsletter-delivery/#all-confirmed-subscribers-receive-new-issues) the type `ConfirmationLinks` is returned from `create_uncomfirmed_subscriber()`, but it is never imported. `use crate::helpers::{spawn_app, ConfirmationLinks, TestApp};` will fix it.

- The repository doesn't match the blog/book for one example in [`src/routes/newsletters.rs`](https://github.com/LukeMathWalker/zero-to-production/blob/c7a4701c28bf668cecaee57767d0395c9fbb5e15/src/routes/newsletters.rs#L78). I believe that should be `#[tracing::instrument(name = "Get confirmed subscribers", skip(pool))]`.

**Comment by LukeMathWalker** [comment]
Thanks for reporting the issue!
This will be fixed in the next release.

**Comment by cldershem** [comment]
I've found another typo in Chap 9. Instead of creating a new issue for each one I will just add to this issue (unless you'd like me to create separate issues, of course).
