### ISSUE TITLE
Chapter 10 issues.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#129]
This issue is catchall issue for Chatper 10.

- In the 3rd code box of [Extracting Credentials](https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-1-1-extracting-credentials) `secrecy` is imported with no mention of it. It took me several minutes to figure out that it's not a module we've written, but a new dependency (I think?).
- In the 3rd code box of [Extracting Credentials](https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-1-1-extracting-credentials) there is an incorrect `use` statement. `use actix_web::http::header::{HeaderMap, StatusCode};` should be `use actix_web::http::{header::HeaderMap, StatusCode};`.
- In [Password Verification -- Naive Approach](https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-2-password-verification-naive-approach) we add, but ever actually run the migration. Adding a note with `sqlx migrate run` is a helpful reminder.
- `sqlx migrate run` reminder needed in [Using a Cryptographic Hash](https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-3-2-using-a-cryptographic-hash) also.
- The code box under "[Let's update it to work with hashed passwords:](https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-3-2-using-a-cryptographic-hash)" will not compile. `
```
error[E0599]: no method named `as_bytes` found for struct `Secret` in the current scope                                                                     
   --> src/routes/newsletters.rs:173:69
173 |     let password_hash = sha3::Sha3_256::digest(credentials.password.as_bytes());
                                                                  ^^^^^^^^ method not found in `Secret<std::string::String>`
```
The line should be: `let password_hash = sha3::Sha3_256::digest(credentials.password.expose_secret().as_bytes());` This is also true for the box following "Let's spare ourselves another migration by using the second option:".
- First code box in [User Enumeration](https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-5-user-enumeration) is missing a `use uuid::Uuid`;` statement.
- Code box above 'This one should pass as well.' in [User Enumeration](https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-5-user-enumeration) should have `TestApp { /../ pub test-user ...}`, the fields listed are already `pub`.

**Comment by LukeMathWalker** [comment]
Thanks for the report!
`secrecy` was introduced in chapter 4 in a recent book release - that's why it's not explained when mentioned in this chapter 😁
