### ISSUE TITLE
Suddenly can no longer compile project

### ISSUE THREAD

**Issue by arkAD93** [LukeMathWalker/zero-to-production#130]
I followed along the book, reached 7.3.8 _Sharing Startup Logic_ section, until I started to struggle due to inconsistency inside code blocks (compiler started to complain EmailClient::new takes 4 parameters, but 3 provided etc)

I decided to go back to the end of 7.3.7 (I quite often do snapshots), but turned out I can no longer compile the code :(

Since then I tried jumping across multiple snapshots, but without any luck.

Also the issue seems to be referring to some issue when building dependency, rather than _'my'_ code itself.

```
 cargo build
    Updating crates.io index
  Downloaded actix-codec v0.4.2
  Downloaded bytestring v1.0.0
  ...
   Compiling actix-http v3.0.0-beta.18
   Compiling sqlformat v0.1.8
   Compiling hyper v0.14.16
   Compiling sqlx-core v0.5.10
   Compiling actix-web v4.0.0-beta.19
error[E0107]: this trait takes 0 generic arguments but 1 generic argument was supplied
   --> /Users/arkad/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.19/src/service.rs:310:6
    |
310 | impl Resource<Url> for ServiceRequest {
    |      ^^^^^^^^----- help: remove these generics
    |      |
    |      expected 0 generic arguments
    |
note: trait defined here, with 0 generic parameters
   --> /Users/arkad/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-router-0.5.0-rc.1/src/resource_path.rs:5:11
    |
5   | pub trait Resource {
    |           ^^^^^^^^

error[E0046]: not all trait items implemented, missing: `Path`
   --> /Users/arkad/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.19/src/service.rs:310:1
    |
310 | impl Resource<Url> for ServiceRequest {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `Path` in implementation
    |
    = help: implement the missing item: `type Path = Type;`

Some errors have detailed explanations: E0046, E0107.
For more information about an error, try `rustc --explain E0046`.
error: could not compile `actix-web` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

```

I'm completely lost with this one, wasn't there before and now I cannot continue. I am stuck - cannot compile any version right now.

I am on Macos, cargo version 1.58.0 (7f08ace4f 2021-11-24).

**Comment by jandillmann** [comment]
I had the same error this morning, can you try to update the `actix-web` dependency to `beta.20`?

```
[dependencies]
actix-web = "=4.0.0-beta.20"
```

This resolved the error for me.

**Comment by LukeMathWalker** [comment]
^ This is the solution. The next release will upgrade as well.

**Comment by jandillmann** [comment]
@LukeMathWalker it seems like `tracing-actix-web` also needs an update, as it depends on `actix-web = "=4.0.0-beta.20"`.

```
[dependencies]
actix-web = { version = "=4.0.0-beta.19", default-features = false }
```

**Comment by LukeMathWalker** [comment]
You can now use version `0.5.0-beta.10` of `tracing-actix-web`.

**Comment by arkAD93** [comment]
Finally compiles! Marking as solved.
