### ISSUE TITLE
Chapter 10.1 Issues.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#131]
- Code box after[One last task left for us: injecting the secret used by our HMACs into the application state.](https://www.lpalmieri.com/posts/session-based-authentication-in-rust/#3-4-5-add-an-hmac-tag-to-protect-query-parameters) requires `secrecy::Secret`.
- Code box after [Let's change login once again to use it:](https://www.lpalmieri.com/posts/session-based-authentication-in-rust/#3-4-5-add-an-hmac-tag-to-protect-query-parameters) requires `secrecy::Secret`.
- Everything involving `Hmac` will not compile with `hmac` v0.11, which is the version explicitly used in this chapter. It will compile with v0.12 with no changes to the code. It appears that hmac is eventually removed, so I'm not gonna spend time troubleshooting this, but it took several hours of me thinking I did something wrong.
- Code box after "One last task left for us: injecting the secret used by our HMACs into the application state:" is missing `use secrecy::Secret`.
- Code box after the last one also needs `use secrecy::Secret`
- Code box after "Let's create a wrapper type to sidestep the issue:" does not compile.  `        .app_data(Data::new(HmacSecret(hmac_secret.clone())))
` should be `            .app_data(Data::new(hmac_secret.clone()))` and `impl Application` needs to be updated to:
```
impl Application {
/* */
pub async fn build /* */
let server = run(
/* */
HmacSecret(configuration.application.hmac_secret),
)?;
```

- Code after "We can now define a verify method on QueryParams itself: " `        mac.verify(&tag)?;` should be `mac.verify_slice(&tag)?;`
- After "We can avoid this issue entirely by making all fields in QueryParams required while QueryParams itself becomes optional:" `query: web::Query<Option<QueryParams>>` may not actually be allowed in `actix-web`. It compiles, but there is a runtime (which always displays on the page, which is the opposite of what we're going for) `Query deserialize error: invalid type: map, expected option`. I believe that error is from `serde::Deserialize` on `QueryParams`. Again, it looks like the final code doesn't use this so I'm moving on from troubleshooting it. There is a chance that it could never work because I'm fairly certain `actix-web` and `serde` don't allow options to be used like that.
- All of the tests in "3.4.9. An Integration Test For Login Failures" have the wrong file path. The repository has everything under `/tests/api/*`.
- Code under "Let's go for the latter - a user being redirected with some dodgy query parameters will see our login page, an acceptable scenario"  has a typo in the file path. It should read `//! src/routes/login/get.rs`
- same typo in code under: "We can now define a verify method on QueryParams itself: it will return the error string if the message authentication code matches our expectations, an error otherwise."
- I'm unable to get the last tests in "3.4.11. An Integration Test For Login Failures - Part 2" to pass because of the previously mentioned `web::Query<Option<QueryParams>>` issue.
- Last code in "3.4.13. How To Delete A Cookie In actix-web" require `use actix_web::cookie::Cookie`.
- Using the `time` crate is unnecessary and gives an error. using ` Cookie::build("_flash", "").max_age(actix_web::cookie::time::Duration::ZERO).finish(),` works
- typo "after having been read - `actix-web-flash-messages` takes of it." should be "after having been read - `actix-web-flash-messages` takes _care_ of it."
- `# base.yaml` should be `# configuration/base.yaml`
- In "4.4.1. Redis In Our Development Setup" `scripts/init_redis.sh` is never run. It will also need to be made executable.
- Adding [`actix-sesion`](https://www.lpalmieri.com/posts/session-based-authentication-in-rust/#4-4-actix-session) took a little finagling with versions. A `cargo clean` and a `cargo update` was able to sort me out eventually.
- Typo: `    .context("Failed to performed a query to retrieve a username.")?;` should bit `    .context("Failed to perform a query to retrieve a username.")?;`.
- Need to add `use change_password` in `//! src/startup.rs
use crate::routes::{change_password, change_password_form};`
- `use actix_web::http::header::LOCATION;` not required in `//! src/routes/admin/password/post.rs` or `//! src/routes/admin/password/get.rs`
- `use actix_web::http::header::LOCATION;` missing in `src/utils`
- box after "The test fails because the request handler panics. Let's fix it:" missing `use::secrecy::ExposeSecret`
- The boxes surrounding "That takes care of the redirect, the first part of the test, but it does not handle the error message:" are slightly misleading. The code cannot compile as-is in order to get the resulting test to pass. `return see_other("/admin/dashboard");` needs to be wrapped with `Ok()`.
- "logged out by mistake due to browser optimisations like link prefetching." isn't exactly accurate. Prefetching only currently happens with `<link>` tags and [not `<a>` tags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ#are_anchor_a_tags_prefetched).
- In "5.2.5. Logout" one code change is unnecessary, it's already the state it's in.
```
//! src/routes/login/post.rs
// [...]
pub async fn login_form(/* */) -> HttpResponse {
    // [...]
    // Display all messages levels, not just errors!
    for m in flash_messages.iter() {
        // [...]
    }
    // [...]
}
```
- `TestApp.post_logout()` is never written, but is called.
- In `compute_password_hash()` it `expose_secret` is missing `    .hash_password(password.expose_secret().as_bytes(), &salt)?`
- Not clear what this refers to, "Migrate the expected input from application/json to application/x-www-form-urlencoded;"
- Using javascript for the logout form is a little odd. Just using a regular form and button works better, has the benefit of being more obvious, and is accessible also.
```
        <li>
          <form name="logoutForm" action="/admin/logout" method="post">
            <input type="submit" value="Logout">
          </form>
        </li>
```

**Comment by cldershem** [comment]
It's very difficult to compare my code to the code that's in the repo for a few reasons. 

- There appears to have been an undocumented refactor at some point. Possibly in the time between chapters, If that is the case, this wouldn't be a problem when someone is reading the book straight through from cover to cover once it's finished.
    - see:
        - https://github.com/LukeMathWalker/zero-to-production/blame/c5bbd6bca250c17e4dd26d9e40c07fa7e1fe4bde/tests/api/helpers.rs#L102
        - https://github.com/LukeMathWalker/zero-to-production/blame/c5bbd6bca250c17e4dd26d9e40c07fa7e1fe4bde/tests/api/helpers.rs#L238 
- I'm not sure if it's RLS or `rustfmt`, but my `use` statements and dependencies are in alphabetical order....this makes it so much easier to spot minor version differences, forgotten imports, etc.

**Comment by cgubbin** [comment]
I'm having two issues with the latest chapter.  When I run locally all the session based tests fail, and I cannot login to the admin dashboard. The errors in the log statements look like this when the correct username and password are supplied to the login form:

```
{"v":0,"name":"zero2prod","msg":"[HTTP REQUEST - EVENT] Error encountered while processing the incoming 
HTTP request: GenericError(NOAUTH: Authentication Required.)","level":50,"hostname":"ChristophersMBP",
"pid":73005,"time":"2022-01-30T19:53:19.835621Z","target":"tracing_actix_web::middleware","line":258,
"file":"/Users/cgubbin/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-
beta.9/src/middleware.rs","http.route":"/login","http.target":"/login","http.flavor":"1.1","otel.kind":
"server","exception.details":"GenericError(NOAUTH: Authentication required.)","otel.status_code":"ERROR",
"http.status_code":500,"request_id":"b9b4002e-170e-4924-99f0-f733fef04a66",
"http.user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/96.0.4664.110 Safari/537.36","exception.message":"Something went wrong when persisting the session 
state.","http.host":"127.0.0.1:8000","http.client_ip":"127.0.0.1","http.scheme":"http","http.method":"POST"}
```

After some troubleshooting I got my all the tests to pass on Circle, so I am confident that I have written the code correctly. I think there is some issue locally with how the actix server is communicating with redis which does not occur on the CI server (i am using macOS locally).

When I connect to the redis instance using `docker exec -it redis_ sh` and run `redis-cli` I can set variables ok. When I enter `auth "password"` it correctly informs me `ERR AUTH <password> called without any password configured for the default user`.

When I connect using redis-cli and the connection string `"redis://127.0.0.1:6379"` from the app configuration I get the error  `NOAUTH: Authentication Required.` which appears in the actix logs.

I am also having a secondary issue on DigitalOcean since adding redis. My project builds but on deployment I get a single line in the log:

```
Error: TLS error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify 
failed:../ssl/statem/statem_clnt.c:1913: (unable to get local issuer certificate)
```
This is presumably also an error from trying to connect to the redis database.

**Comment by LukeMathWalker** [comment]
Thanks for the very detailed feedback @cldershem  😁 Slowly working my way through it.

On some of the points you raised:

- It should indeed have been `hmac` `0.12`;
- The correct injection type is `Option<query: web::Query<QueryParams>>`, which behaves as expected in the book.
