### ISSUE TITLE
changing macro for tokio executor

### ISSUE THREAD

**Issue by mmajass** [LukeMathWalker/zero-to-production#134]
Hi, 

it would be great to get some insight as to why #[actix_web::main] was changed to #[tokio::main]. I understand actix-web also runs on Tokio runtime, just would like to know the reasoning why use one over the other.

For those who don't like to click on [links](https://github.com/LukeMathWalker/zero-to-production/commit/7eedba1fee9a2344135dc6646ef445c1898b1858#r66929867):

`-  #[actix_web::main]`
`+ #[tokio::main]`

Thanks

**Comment by LukeMathWalker** [comment]
It makes it clearer that there is nothing special about the `actix-web` macro. It's a teaching choice - you can choose whichever you prefer in your own projects 😁
