### ISSUE TITLE
suggestion: clean up databases during integration test teardown

### ISSUE THREAD

**Issue by lukehsiao** [LukeMathWalker/zero-to-production#135]
I've enjoyed the content on integration tests in the book. Particularly, how you create new databases for each test such that tests can still be run in parallel.

I know you've intentionally not cleaned up these databases thus far. That said, I think doing so can be nice, especially when testing a lot locally.

One way to do so is to clean up in the Drop trait for the TestApp. If we implement a "tear-down" in the drop trait, it will get called even if a test panics mid-way through, ensuring that the temporary database create is cleaned up.

In case it is helpful to other readers, or you like the idea, here is one attempt at such an implementation (assuming the same TestApp and testing infrastructure outlined in this repository):

```rs
// Test tear down happens on drop, which will happen even if a test fails/panics mid-way.
impl Drop for TestApp {
    fn drop(&mut self) {
        // This is a hacky workaround to calling async code from this sync Drop trait to clean up.
        let (tx, rx) = std::sync::mpsc::channel();
        let db_name = self.db_name.clone();

        std::thread::spawn(move || {
            let rt = Runtime::new().unwrap();
            rt.block_on(async {
                let config = get_config().expect("Failed to read configuration");
                let mut conn = PgConnection::connect_with(&config.database.without_db())
                    .await
                    .expect("Failed to connect to Postgres");

                // Kick off open sessions (from the spawned app). This could be replaced
                // by WITH (FORCE) in Postgres 13+.
                conn.execute(&*format!(
                    "SELECT pg_terminate_backend(pg_stat_activity.pid)
                    FROM pg_stat_activity
                    WHERE datname = '{}'
                      AND pid <> pg_backend_pid();",
                    db_name
                ))
                .await
                .expect("Failed to disconnect other sessions");

                conn.execute(&*format!("DROP DATABASE \"{}\";", db_name))
                    .await
                    .expect(&format!("Failed to drop temporary database: {}", db_name));
                debug!("Dropped database: {db_name}");
                let _ = tx.send(());
            })
        });

        let _ = rx.recv();
        debug!("ran test teardown");
    }
}
```

I admit, it isn't pretty spawning a thread just to clean up. I'm a rust newbie, so if there are ways to implement this behavior more cleanly, I'd love to learn about it.

**Comment by LukeMathWalker** [comment]
This has been brought up several times - it's unfortunately extremely difficult (if not impossible) to implement this reliably (e.g. what happens when you CTRL+C while tests are running?).

**Comment by lukehsiao** [comment]
Fair enough :). 

FWIW if anyone else happens on this, I followed the tutorial, but used axum instead of actix, and axum has a way to register a graceful shutdown handler to catch things like ctrl+c. So, the code snippet above, despite being a bit of a hack, has been working wonderfully for us.

**Comment by nextuponstream** [comment]
While re-reading the book and wanting to implement my own integration test with axum+postgres+sqlx, I stumbled upon `sqlx::test` [macro](https://docs.rs/sqlx/0.7.3/sqlx/attr.test.html). It just arrived a few months after the last comment (according to the [changelog](https://github.com/launchbadge/sqlx/blob/31e541ac7a9c7d18ee2b3b91c58349e77eac28f7/CHANGELOG.md?plain=1#L536).

If you grant superuser privileges to your dev database user, it allows sqlx::test to auto-setup+teardown a test database for each tests. After using it myself, it feels pretty convenient not having to write setup+teardown methods. There's probably drawbacks (test speed?) though but I think it's worth mentionning here that it exists.
