### ISSUE TITLE
Typo in 3.8.5.4

### ISSUE THREAD

**Issue by birdsarah** [LukeMathWalker/zero-to-production#137]
> What is the type of `saved`? The `query!` macro returns an anonymous record type: a struct definition is generated at compile-time after having verified that the query is valid, with a member for each column on the result (i.e. `save.email` for the `email` column).

Suggest:

`saved.email` so that you continue referencing the `saved` variable already introduced.

**Comment by LukeMathWalker** [comment]
Thank you!
