### ISSUE TITLE
Cargo-chef at Dockerfile: unknown variant `2021`, expected `2015` or `2018` for key `package.edition` 

### ISSUE THREAD

**Issue by drconopoima** [LukeMathWalker/zero-to-production#140]
Hello.

I'm trying to build the Dockerfile at root-chapter-06 with the following cargo-chef:

docker.io/lukemathwalker/cargo-chef:latest-rust-1.53.0

I receive the following error:

```text
[2/4] STEP 3/3: RUN cargo chef prepare  --recipe-path recipe.json
Error: Failed to compute recipe

Caused by:
    0: unknown variant `2021`, expected `2015` or `2018` for key `package.edition` at line 33 column 1
    1: unknown variant `2021`, expected `2015` or `2018` for key `package.edition` at line 33 column 1
Error: error building at STEP "RUN cargo chef prepare  --recipe-path recipe.json": error while running runtime: exit status 1
```

I'm unsure what the cargo-chef package is offering, for caching of layers I'm using ideas slightly from [this article](https://dev.to/rogertorres/first-steps-with-docker-rust-30oi):

```yaml
FROM docker.io/library/rust:1.59-slim-bullseye as builder

RUN USER=root cargo new --bin zero-to-production

WORKDIR /newsletter-rs

RUN touch ./src/lib.rs

COPY ./Cargo.toml ./Cargo.lock ./

# layer caching deps:
RUN cargo build --release

# Delete the empty project files
RUN rm ./src/*.rs ./target/release/deps/zero_to_production* ./target/release/deps/libzero_to_production* ./target/release/libzero_to_production* ./target/release/zero-to-production*
```

The runtime step would be equivalent

I wasn't able to build using chef by changing the Cargo.toml edition to 2018 due to serde-aux 3.0.1 requiring 1.59
```text
error: failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde-aux-3.0.1/Cargo.toml`

Caused by:
  feature `edition2021` is required
```

**Comment by drconopoima** [comment]
I think I resolved with the following pull request:

https://github.com/LukeMathWalker/zero-to-production/pull/142/files

It still doesn't build for me because I don't have sqlx binary locally and it's not picking up on the sqlx-data.json (I'm following up the book with tokio-postgres).

```sh
[1/2] STEP 10/10: RUN cargo build --release --bin zero2prod
   Compiling zero2prod v0.1.0 (/zero-to-production)
error: `DATABASE_URL` must be set, or `cargo sqlx prepare` must have been run and sqlx-data.json must exist, to use query macros
  --> src/routes/subscriptions.rs:45:5
```

**Comment by LukeMathWalker** [comment]
I don't think that pull request was necessary - it should be enough to bump the Rust version in the base Docker image. The latest book version is on 1.59.0.

**Comment by drconopoima** [comment]
Excuse me, I saw the error while not knowing you built cargo-chef yourself and thought of a dependency having gotten stale and a MR being useful. I probably cloned in between the 2021 version being set up and the Dockerfile referenced the older image
