### ISSUE TITLE
5.4.4 "Failed to read configuration.: invalid digit found in string"

### ISSUE THREAD

**Issue by suchapalaver** [LukeMathWalker/zero-to-production#147]
```
=> Uploaded the built image to the container registry
=> Build complete
thread 'main' panicked at 'Failed to read configuration.: invalid digit found in string', src/main.rs:15:45
```
Even though I've used the `#[serde(deserialize_with = "deserialize_number_from_string")]` custom deserialization function with `serde-aux` I'm still getting the error above when I deploy to DO. 

I have checked and rechecked how I've followed along. Can anyone help?

My repo for the project is [here](https://github.com/suchapalaver/newsletter).

Thanks in advance if anyone has any ideas.

**Comment by suchapalaver** [comment]
This was my bad. Without looking ahead at the outset I named my repo 'newsletter' instead of 'zero2prod', coincidentally the project as in the book names its database 'newsletter'. All fixed again. Learning so much!

**Comment by EJunger** [comment]
Hey @suchapalaver could you provide a little more context on your fix? I'm having the exact same issue deploying on DO. 

I've changed around my repo name (from newsletter) and db name but I'm still getting the same error. Sorry it this is out of the blue, I'm going crazy trying to fix this. :(
