### ISSUE TITLE
https://my-api.com/subscriptions/confirm exists

### ISSUE THREAD

**Issue by max-block** [LukeMathWalker/zero-to-production#149]
There is the code in the book:
```
pub async fn send_confirmation_email(email_client: &EmailClient, new_subscriber: NewSubscriber) -> Result<(), reqwest::Error> {
    let confirmation_link = "https://my-api.com/subscriptions/confirm";

```
It should first fail in tests, because of a non-existing address. But it exists and returns Response=200.

It's better to change the link "https://my-api.com/subscriptions/confirm" to something "https://there-is-no-such-a-domain.com/subscriptions/confirm"

P.S. It's about the chapter 7.7.5.1 Red Test

**Comment by LukeMathWalker** [comment]
Thanks, this will be patched in the next release!
