### ISSUE TITLE
Mentioned that offline was added in chapter 5

### ISSUE THREAD

**Issue by pickfire** [LukeMathWalker/zero-to-production#15]
I was following the blog post in https://www.lpalmieri.com/posts/2020-11-01-zero-to-production-5-how-to-deploy-a-rust-application/ but there was an issue following such that the previous chapters did not mention that `offline` feature needed to be added in the current chapter. It would be good to mention that in the blog post.

https://github.com/LukeMathWalker/zero-to-production/blob/master/chapter05/Cargo.toml#L21

**Comment by LukeMathWalker** [comment]
Good call - I amended both the blog post and the book :grin:
