### ISSUE TITLE
Suggested rewrite to the README due to Xcode error

### ISSUE THREAD

**Issue by terryo-iotandwearablesguy** [LukeMathWalker/zero-to-production#152]
Awesome book - thank you for authoring it.  When using the MacOS Monterey 12.4 I don't use Xcode due to the massive size, so  when trying to run the command: "brew install michaeleisel/zld/zld"

I got the following errors:
————————————————————
/usr/local/opt/cmake/bin/cmake
xcodebuild -project ld/zld.xcodeproj -scheme zld -derivedDataPath build -configuration Release build ONLY_ACTIVE_ARCH=YES
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build_homebrew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michaeleisel/homebrew-zld/issues
———————————————————————————

This problem happens when xcode-select developer directory was pointing to /Library/Developer/CommandLineTools when a full regular Xcode was required (happens when CommandLineTools are installed after Xcode)
Solution:

Perhaps your README should include:

"If you don't have Xcode already installed or an older copy please do the following:

	1	Install Xcode (get it from https://appstore.com/mac/apple/xcode) if you don't have it yet.
	2	Accept the Terms and Conditions. Command: sudo xcodebuild -license accept  
	3	Ensure Xcode app is in the /Applications directory (NOT /Users/{user}/Applications).
	4	Point xcode-select to the Xcode app Developer directory using the following command: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
	5	Then finally the command: brew install michaeleisel/zld/zld

Note: Make sure your Xcode app path is correct.
	•	Xcode: /Applications/Xcode.app/Contents/Developer"

It worked for me this morning.  

Referencing: https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786

**Comment by LukeMathWalker** [comment]
Happy to include it! Can you open a PR?

**Comment by terryo-iotandwearablesguy** [comment]
Luca;

Sorry but what is a PR?  My Director of Operations purchased 8 copies yesterday, so if it’s a Purchase Request, we did that already.  The key was CE8373F5-B2D54562-8FA757E3-6B0F6BA8.

Terrance O’Shea, Ph.D. O.E.
V.P. of Engineering
Squire Solutions, Inc.
***@***.***
(808)343-5151
www.squiresolutions.com 

The information contained in this communication (including any attachments) is confidential and is intended only for the specific purpose and use of the addressee.  It is the property of Squire Solutions, Inc.  Any unauthorized use, disclosure or copying of this communication or any part thereof is strictly prohibited and may be unlawful.  If you have received this communication in error, please notify us immediately by return email and then erase and destroy this communication and all copies thereof, including all attachments.

**Comment by terryo-iotandwearablesguy** [comment]
Sorry what is a PR? My Operations Director Jay from SquireSolutions purchased 8 copies yesterday.
