### ISSUE TITLE
Local docker container error

### ISSUE THREAD

**Issue by w1n5t0n99** [LukeMathWalker/zero-to-production#156]
Hello,

Attempting to run the container locally fails to connect to the local Redis container initialized with init_redis.sh. 
The error returned is
 Error: Could not connect to Redis database

Caused by:
    Connection refused (os error 111)

The application runs fine locally when not in a container.

**Comment by bendoerry** [comment]
I managed to get this working by using the name of the redis container in the URI instead of `127.0.0.1`.
I'm currently passing that to my app instances using the environment variable config override:
```
APP_REDIS_URI="redis://<REDIS_CONTAINER_NAME>:6379"
```
