### ISSUE TITLE
Installing sqlx-cli 0.6.0  needs to set native-tls feature

### ISSUE THREAD

**Issue by 22earth** [LukeMathWalker/zero-to-production#159]
According to the document of [sqlx-cli](https://crates.io/crates/sqlx-cli)
```bash
# only for postgres
cargo install sqlx-cli --no-default-features --features native-tls,postgres
```
https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-03-part1/scripts/init_db.sh#L13

`cargo install --version=0.6.0 sqlx-cli --no-default-features --features postgres` would output this error
```
   |
9  | / compile_error!(
10 | |     "one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
11 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
12 | |      'runtime-tokio-rustls'] must be enabled"
13 | | );
   | |_^
```

**Comment by LukeMathWalker** [comment]
Fixed in #70ff9c358aed050168b499a46eaa5a14afdaaae0
