### ISSUE TITLE
Chapter 7: database migration issue on production 

### ISSUE THREAD

**Issue by ra2u18** [LukeMathWalker/zero-to-production#163]

**Comment by LukeMathWalker** [comment]
I am not sure I follow - when do these errors pop up? When building the Docker image?

**Comment by ra2u18** [comment]
These error pop up when I push my code to github and DigitalOcean rebuilds my docker image

**Comment by ra2u18** [comment]
I deleted my application entirely from DigitalOcean and then ran `doctl apps create --spec spec.yaml`. Now after finishing chapter 7 in the book, I get multiple issues. I guess this is related to db migrations, but I m not sure how to fix it.

**Comment by ra2u18** [comment]
fixed by updating sqlx offline file
