### ISSUE TITLE
Chapter 05: no queries was found by `sqlx prepare`

### ISSUE THREAD

**Issue by imag1ne** [LukeMathWalker/zero-to-production#167]
When I executed `cargo sqlx prepare -- --lib`, there is a warning: "no queries found; please ensure that the `offline` feature is enabled in sqlx", even if I enabled the `offline` feature for sqlx.

Then I pulled the code of this repository, `sqlx prepare` worked. However, if I delete the Cargo.lock file and do it again. `sqlx prepare` can no longer find the queries and its output file sql-data.json only shows the following content:

```json
{
  "db": "PostgreSQL"
}
```

Is it caused by the version of the dependencies? How can I fix it?

**Comment by LukeMathWalker** [comment]
What version of `sqlx` and `sqlx-cli` are you using?

**Comment by imag1ne** [comment]
> What version of `sqlx` and `sqlx-cli` are you using?

Problem was solved by upgrading sqlx-cli from 0.6.1 to 0.6.2. Thanks for your hint! :)
