### ISSUE TITLE
Chapter 3: Have to use nightly toolchain to compile sqlx 0.6

### ISSUE THREAD

**Issue by anklinuxboy** [LukeMathWalker/zero-to-production#168]
I'm using Rust 1.64 stable. Adding the sqlx 0.6 dependency doesn't compile the project.

**Cargo.toml**
```
[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
config = { version = "0.13", default-features = false, features = ["yaml"] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
sqlx = { version = "0.6", features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
```

Using 
`cargo +nightly build`
works fine.

Putting it here if other people are running into a similar issue

**Comment by LukeMathWalker** [comment]
`sqlx` does not require nightly.
What error is the compiler returning you?

**Comment by anklinuxboy** [comment]
I get this error

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 #![cfg_attr(provide_any, feature(provide_any))]
```

```
> rustc --explain E0554
Feature attributes are only allowed on the nightly release channel. Stable or
beta compilers will not comply.

Erroneous code example:

#![feature(lang_items)] // error: `#![feature]` may not be used on the
                        //        stable release channel

If you need the feature, make sure to use a nightly release of the compiler
(but be warned that the feature may be removed or altered in the future).
```

**Comment by LukeMathWalker** [comment]
Can you provide a link to your repository?

**Comment by anklinuxboy** [comment]
yup. This one - https://github.com/anklinuxboy/Zero2ProdRust

Appreciate your support!

**Comment by LukeMathWalker** [comment]
Just cloned the repository and checkout the PR - it builds just fine for me on the latest Rust stable release. 
Can you post the output of `rustup show` from inside your project directory?

**Comment by anklinuxboy** [comment]
That's strange. Here's the output of rustup show

```
> rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/ankitsharma/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

I merged the PR into master and tried again this morning, but still getting the same error 😕

**Comment by LukeMathWalker** [comment]
I'm honestly confused about what is going on here.

**Comment by anklinuxboy** [comment]
I'll try creating a separate clone and see if I get the same issue.

**Comment by anklinuxboy** [comment]
I updated to macOS Ventura and after updating, `cargo build` works fine. No idea what happened there lol 🤔 

Closing this

**Comment by the-undefined** [comment]
I had the same issue on:

```
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

But after `rustup update`, on

```
rustc 1.65.0 (897e37553 2022-11-02)
```

`cargo check` worked fine. Wondered if you had installed the latest rustc when updating to Ventura which is why I tried this out.
