### ISSUE TITLE
Publish Links Reference on Github

### ISSUE THREAD

**Issue by anklinuxboy** [LukeMathWalker/zero-to-production#170]
Hi Luke,

Is it possible to publish the links reference on Github? It will remove the friction for people who're using the print book.

**Comment by LukeMathWalker** [comment]
Hi!
I've considered this for a while, but it's unfortunately fairly complicated - the book is often updated and you'd end up with a reference on GitHub that might not match the one on print.
Therefore I've opted not to move forward with this.
