### ISSUE TITLE
Chapter 3, pg 38. E0061 on Run()?.await in main.rs

### ISSUE THREAD

**Issue by Travizm** [LukeMathWalker/zero-to-production#171]
Im up to pg 38 where we need to update main.rs and run cargo check. 

Im trying to figure out what i've done wrong here and note that by the end of the chapter you have introduced an address fn into main. 

Here's the cargo test  output:
╰─ cargo test                                                                 ─╯
   Compiling zero2prod v0.1.0 (.../zero2prod)
error[E0061]: this function takes 1 argument but 0 arguments were supplied
  --> src/main.rs:6:5
   |
6  |     run()?.await
   |     ^^^-- an argument of type `&str` is missing
   |
note: function defined here
  --> /.../zero2prod/src/lib.rs:10:8
   |
10 | pub fn run(address: &str) -> Result<Server, std::io::Error> {
   |        ^^^
help: provide the argument
   |
6  |     run(/* &str */)?.await

**Comment by LukeMathWalker** [comment]
Can you provide a link to your repository?

**Comment by Travizm** [comment]
Yes I can many thanks: [Pg 38 repo](https://github.com/Travizm/zero2p)

**Comment by codewing** [comment]
You're not passing an address `&str` to your run method `run(address: &str)` in the main.rs

**Comment by codewing** [comment]
@Travizm if this did solve the issue you can close this issue here aswell

**Comment by Travizm** [comment]
Thanks - will close.
