### ISSUE TITLE
General question on CI workflow

### ISSUE THREAD

**Issue by tkline615** [LukeMathWalker/zero-to-production#177]
At the end of chapter 1 it suggests to leverage one of the four CI configuration templates provided on the gist: https://gist.github.com/LukeMathWalker 

After reviewing the different branches on the project, it looks like GitHub Actions was the chosen CI solution for the book.  As such I'd like to follow along and attempt the same CI workflow.  It appears that each branch / chapter has evolving changes in the .yaml files.  What is unclear to me, is if I'm attempting to follow the book and use the same CI pipeline approach, should I be altering the .yaml files / pushing them to the main branch of my project at the same time?

Apologies but this is new to me and I'm a bit confused.  I'm trying to follow the same general approach you would take when modifying / making the decision to alter your CI configuration files as the project evolves.

**Comment by LukeMathWalker** [comment]
The YAML configuration in this repository has been tweaked to support the "1 branch per snapshot" model.
The book points out when the CI definition needs to be changed (and how).

**Comment by tkline615** [comment]
Thanks Luke, really appreciate the response and I got it up and running.  The book is fantastic!
