### ISSUE TITLE
Updating Cargo Commands In Future Releases

### ISSUE THREAD

**Issue by Ktoks** [LukeMathWalker/zero-to-production#179]
For the sake of those who don't have an efficient development machine with speedy compilation and for those with environmental concerns- I'd like to request to replace `cargo install` commands with `cargo binstall` commands wherever present in the book and documentation.

_cargo binstall_ finds and installs binaries similar to _apt_. It is also supported by `cargo install-update -a` as well.

By doing so, I was able to cut the processing time used installing new tools and dependencies to _nearly_ none.

**Comment by LukeMathWalker** [comment]
Until https://github.com/cargo-bins/cargo-binstall/issues/1 is resolved in some direction, I'll keep recommending `cargo install` as the default installation method. 
As an educator, I should always recommend the most secure option as default - users can make different trade-offs if they want to.
