### ISSUE TITLE
Github CI: actions-rs is unmaintained and fails CI

### ISSUE THREAD

**Issue by Kaltxi** [LukeMathWalker/zero-to-production#186]
It seems that `actions-rs` is unmaintained and has problems in particular with deprecation of node 12, `tarpaulin` and `clippy-check`. The latter two throw errors which fail CI:

```
 Code coverage
Couldn't find a release tarball containing binaries for latest

 Clippy
Resource not accessible by integration
```
I looked at this repo's recent changes to CI, but they seem to use the same config. Is there a way to fix those errors, or maybe switch to other actions?

**Comment by LukeMathWalker** [comment]
We could switch to other actions - I have it on my backlog of upcoming book updates!

**Comment by Kaltxi** [comment]
Alright, nice! Maybe you have some recommendations as to which actions to use for code coverage and clippy?

**Comment by LukeMathWalker** [comment]
The CI has been updated on all branches!
