### ISSUE TITLE
Adding comments in general.yml file

### ISSUE THREAD

**Issue by jmevel** [LukeMathWalker/zero-to-production#194]
Hi everybody,

So I'm at section `3.8.5.5 Updating Our CI Pipeline` of the book and I followed the link to the new [general.yml Github Action](https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-03-part1/.github/workflows/general.yml) and now I'm like `WTF...`

So much is happening in this file and there's no comments neither in the file nor in the book...
Would that be possible to create a commented version of the file? 
I really would like to understand what's going on here

Thank you

**Comment by jmevel** [comment]
Ok at the end it took me half a day but I did it. Here's [my general.yml file with comments](https://gist.github.com/jmevel/0f9a076ec6032065a7a1c70f862cf6cd)
There's still one thing I don't understand in the [original file](https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-03-part1/.github/workflows/general.yml) is why sometimes we install `libpq-dev` like for the `Clippy` and `test` workflows but for the `Code coverage` one we install `postgresql-client` instead.

**Comment by LukeMathWalker** [comment]
Hey!
Happy to merge the commented version if you are willing to contribute it! I haven't gone too much into it because most of the things in there are very specific to the CI system being used, which is not the focus of the book per se.

> There's still one thing I don't understand in the [original file](https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-03-part1/.github/workflows/general.yml) is why sometimes we install libpq-dev like for the Clippy and test workflows but for the Code coverage one we install postgresql-client instead.

Mostly an historical artefact, I should amend it for consistency.

**Comment by jmevel** [comment]
> Hey! Happy to merge the commented version if you are willing to contribute it!

My file is now a bit different from yours but yes that's a good idea, I'll try to submit a PR sometime this week or maybe next one. Even though I'm familiar with git, this would be my very first PR on a public repository!

> Mostly an historical artefact, I should amend it for consistency.
Oh ok I see, do you think I should change this at the same time in my PR or should it be only a `refactor` one, adding comments only?
I guess using `libpq-dev` would be better in the CI since it's supposed to be smaller than `postgresql-client`. Am I right or is it the opposite?

**Comment by LukeMathWalker** [comment]
We can close this now since the PRs have been merged. Thanks for contributing!
