### ISSUE TITLE
Wrong code shown in chapter 3.5 part 3.6

### ISSUE THREAD

**Issue by cedeerwe** [LukeMathWalker/zero-to-production#20]
![Screenshot from 2020-12-06 12-48-27](https://user-images.githubusercontent.com/11530208/101279283-7a007c00-37c1-11eb-93e1-4cc79fdc8bfd.png)

There is `pool` in the function definition and `connection` in the body. 

Great job with the book!

**Comment by LukeMathWalker** [comment]
Thanks for reporting, this is fixed now!
