### ISSUE TITLE
Clean architecture and DB transactions in the same DDD bounded context?

### ISSUE THREAD

**Issue by frederikhors** [LukeMathWalker/zero-to-production#203]
Hi @lpalmieri, your work is amazing! Thanks a lot!

I have a question before buying your book: do you explain how to solve the "famous" problem in clean architecture on the separation between the service level and the repository level using DB transactions without leaking DB implementations details on the service level?

I explained the issue in the README of this repository: https://github.com/frederikhors/rust-clean-architecture-with-db-transactions (Issue number 2).

Thank you very much in advance.

**Comment by LukeMathWalker** [comment]
No, we don't get into the weeds of clean architecture in the book. 

I have thoughts on the subject (and its declination in Rust), but never actually invested the time of writing them down :)

**Comment by LukeMathWalker** [comment]
No, we don't get into the weeds of clean architecture in the book. 

I have thoughts on the subject (and its declination in Rust), but never actually invested the time of writing them down :)

**Comment by LukeMathWalker** [comment]
Speaking of your problem #2 specifically, the solution I have used in the past is having a "unit of work" associated type on the repository trait.

Each implementation sets it to whatever type they prefer for transactions and the domain code remains blissfully unaware of the specifics.
There are some caveats in terms of ergonomics, but it largely works if that's what you want to do.

**Comment by frederikhors** [comment]
> I have thoughts on the subject (and its declination in Rust), but never actually invested the time to write them down :)

Can we leave this open until you do?

> the solution I have used in the past is having a "unit of work" associated type on the repository trait

Do you have any example?

The difficulty is that the service layer can call methods which needs DB transactions and methods which not... An example would be great.

Thanks in advance.

**Comment by LukeMathWalker** [comment]
> Can we leave this open until you do?

This repository is focused on issues with the book and I'm afraid this is off topic here 😁 

> Do you have any example?

I don't have time to fully flesh it out now, but something along these lines:

```rust
trait Repository {
   type UnitOfWork;

   #[must_use]
   fn begin_uow(&self) -> Self::UnitOfWork;
   // Take UoW by value, to finalize it.
   fn commit(&self, uow: Self::UnitOfWork) -> /* */;

   // Take UoW by reference, to allow combining multiple actions into the unit
   fn method_that_needs_transaction(&self, uow: &Self::UnitOfWork) -> /* */;
   fn method_that_does_not_need_a_transaction(&self) -> /* */;
}
