### ISSUE TITLE
Circle CI failures with `circleci/rust`

### ISSUE THREAD

**Issue by DennisTheMenace780** [LukeMathWalker/zero-to-production#209]
I just started up with Zero2Prod and tried running the [provided CircleCI config](https://gist.github.com/LukeMathWalker/6153b07c4528ca1db416f24b09038fca) as-is. It seems that CircleCI's `circleci/rust` Rust images has [been replaced with by](https://circleci.com/developer/images/image/cimg/rust?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-tROAS-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAjwjYKjBhB5EiwAiFdSfnAkFIGKJfbZcNx8jk3nosM6FjapNcv2qB2w8ub3mH0DAx94t28sAxoCTwoQAvD_BwE) the `cimg/rust` series of images. The result of this seems to be that using the `circleci/rust` image causes package failures on the build step that require later versions of Rust. 

I tried replacing the image using `- image: cimg/rust:1.68.0` (just to match the Rust version I have locally), and upon doing so, the Security Step fails on the `Cache Permission` with the following: `^@^@chown: cannot access '/usr/local/cargo': No such file or directory`. I was thinking that maybe in the `cimg/rust:1.68.0` image that cargo is installed somewhere else, but since I am working on a Mac machine I can't seem to run the image and inspect much further.

Curious if you have any ideas as to why this might be happening, and how we can resolve it? Once we find a fix then I can open up a PR and make a contribution. 

Docker and setting up CI/CD pipelines is new for me, so any advice and tips on debugging would be greatly appreciated!

**Comment by DennisTheMenace780** [comment]
So I actually ended up fixing this shortly after. What would be the best way to put in a PR for your Gist on the CircleCI config?

**Comment by LukeMathWalker** [comment]
If you link the fixed config I can update the gist on my own 👍🏻

**Comment by DennisTheMenace780** [comment]
https://github.com/DennisTheMenace780/newsletter/blob/master/.circleci/config.yml

**Comment by LukeMathWalker** [comment]
Updated!
Thanks again 😁
