### ISSUE TITLE
Wrong imports in code-block chapter 3.5 part 3.6

### ISSUE THREAD

**Issue by cedeerwe** [LukeMathWalker/zero-to-production#21]
![Screenshot from 2020-12-06 13-46-12](https://user-images.githubusercontent.com/11530208/101280475-8d174a00-37c9-11eb-8b42-0c3659822297.png)

The `Arc` from imports is not used in the code.

Also the comment `Wrap the pool in an Arc smart pointer` is slightly misleading, as we are wrapping it in `web::Data`. 

A sidenote, I have spent quite some time trying to figure out what is wrong after forgetting to update `Arc` to `web::Data` in the `run` function. It actually compiled, but the subscribe tests returned status 500 without any more information. Might be worth mentioning it more explicitly in the text, as the related small "exercise" is not so interesting -- the compiler nor the errors are pointing you to the right direction. I started comparing my code to your 1:1 and that is the only way I could find this inconsistency.

**Comment by LukeMathWalker** [comment]
I have fixed the unused import and improved the code comment. Thanks for reporting the issue :bow:
