### ISSUE TITLE
Failed to select a version for the requirement `tracing-bunyan-formatter = "^0.3"`

### ISSUE THREAD

**Issue by MagiMats** [LukeMathWalker/zero-to-production#210]
When running this command (p114):
sudo docker build --tag zero2prod --file Dockerfile . 

I get this error
` Updating crates.io index
error: failed to select a version for the requirement 'tracing-bunyan-formatter = "^0.3"'
candidate versions found which didn't match: 0.3.6, 0.3.4, 0.3.3, ...
location searched: crates.io index
required by package 'zero2prod v0.1.0 (/app)'
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101`

Is this a problem with my installation or my docker container
Because when I just run cargo build --release in my terminal I don't get any errors

**Comment by MagiMats** [comment]
Downgrading to 0.2 didn't compile anymore

**Comment by MagiMats** [comment]
I found this fix for none docker containers but don't know how I would execute something like this in a docker container since I'm quite a newbie. https://blog.illixion.com/2021/10/fix-failed-to-select-a-version-cargo/

**Comment by LukeMathWalker** [comment]
Use the latest version of the `cargo-chef` base image and it should be gone—it boils down to `cargo` being really slow at downloading the index when using the `git` registry, which is fixed by switching to the `sparse` registry, which the latest `cargo-chef` image defaults to for you.

**Comment by LukeMathWalker** [comment]
Basically,
`FROM lukemathwalker/cargo-chef:latest-rust-1.69.0 as chef` (instead of `1.59.0`) should do the trick.

**Comment by MagiMats** [comment]
Thank you very much!!! 
Btw your this book is really awesome, Exactly what I was looking for.
