### ISSUE TITLE
Replace claim crate with claims due to it's "unmaintained" status

### ISSUE THREAD

**Issue by Pyromanser** [LukeMathWalker/zero-to-production#215]
``` console
hello@world:~$ cargo audit
...
Crate:     claim
Version:   0.5.0
Warning:   unmaintained
Title:     `claim` is Unmaintained
Date:      2022-12-04
ID:        RUSTSEC-2022-0077
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0077
Dependency tree:
claim 0.5.0
└── zero2prod 0.1.0
...
```

There is issue about it in `claim` repo:
https://github.com/svartalf/rust-claim/issues/12

I followed the advice and switched to `claims`.
https://github.com/mattwilkinsonn/rust-claims

**Comment by LukeMathWalker** [comment]
This has been fixed a while ago: https://github.com/LukeMathWalker/zero-to-production/blob/d6f478d88b718f906638d4010b8e60b5348388ea/Cargo.toml#L46

Are you reading the last version of the book?
