### ISSUE TITLE
Chapter 4.5.9 Removing Unused Dependencies : cargo install cargo-udeps error, `use of unstable library feature 'once_cell'`

### ISSUE THREAD

**Issue by zigang93** [LukeMathWalker/zero-to-production#217]
```zsh
error[E0658]: use of unstable library feature 'once_cell'
   --> /Users/tanzigang/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.72.2/src/cargo/util/mod.rs:215:9
    |
215 |     use std::sync::OnceLock;
    |         ^^^^^^^^^^^^^^^^^^^
    |
note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
```

**Comment by ttys3** [comment]
this is as expected.

as  https://github.com/est31/cargo-udeps

> While compilation of this tool also works on Rust stable, it needs Rust nightly to actually run.

usage:

```shell
cargo +nightly udeps
```

**Comment by zigang93** [comment]
> this is as expected.
> 
> 
> 
> as  https://github.com/est31/cargo-udeps
> 
> 
> 
> > While compilation of this tool also works on Rust stable, it needs Rust nightly to actually run.
> 
> 
> 
> usage:
> 
> 
> 
> ```shell
> 
> cargo +nightly udeps
> 
> ```
> 
> 

But it happens on install.. not run

**Comment by LukeMathWalker** [comment]
What version of Rust do you have installed? (`cargo --version` will tell you)

**Comment by zigang93** [comment]
@LukeMathWalker I refer to official docs.. it was success installed with this commands `cargo install cargo-udeps --locked
`

**Comment by LukeMathWalker** [comment]
By running `cargo install cargo-udeps` `cargo` pulls in the latest version of `cargo-udeps`' dependencies.
They require a version of Rust that is stable, but newer than the one you have installed, therefore the error.
