### ISSUE TITLE
oversized release artifact

### ISSUE THREAD

**Issue by danirdd92** [LukeMathWalker/zero-to-production#218]
I'm not really sure why, but I get anywhere between 1.4 to 2.5gigs worth of build artifact after cargo build --release
there's absolutely no way it should be that way

**Comment by LukeMathWalker** [comment]
Quite possible that's correct, if you are counting the entire target folder.
But the binary itself is tiny in comparison—see chapter 5 when we talk about Docker image sizes.

**Comment by danirdd92** [comment]
@LukeMathWalker is the binary the only thing that's needed to run the application? what is the purpose of the rest of the artifacts?

**Comment by LukeMathWalker** [comment]
Yes, binaries are self-contained. 
The rest of the artefacts are the outputs of intermediate steps which speed up the following compilation runs.
