### ISSUE TITLE
Chapter 4 - minor improvement suggestions

### ISSUE THREAD

**Issue by cedeerwe** [LukeMathWalker/zero-to-production#22]
![Screenshot from 2020-12-06 19-07-33](https://user-images.githubusercontent.com/11530208/101288359-70453b80-37f6-11eb-8f93-003a8e7ddda6.png)

Following the tutorial in the part 3.3 I get a deprecation warning:
```
warning: use of deprecated function `env_logger::from_env`: Prefer `env_logger::Builder::from_env()` instead.
```
Also, the `Ok(())` is confusing, as the last line of my main is 
```
run(listener, connection_pool)?.await
```
based on the previous chapter.

In the part where you add `tracing-futures`, the next codeblock should perhaps also show
```
use tracing_futures::Instrument;
```
as it is required and is part of the diff to the previous version.

Some food for thought: when I found this series for the first time (through arewewebyet) and read the introduction, I figured that this series is actually not for me. I have never built a backed system, nor do I plan to build a distributed system anytime soon, so I backed up. After couple of days I gave it a second shot and figured out that this is actually an amazing learning experience about how to build a well organized and reliable web app even for somebody, who has never ever built a web app before. So maybe think about it, change the wording a little bit. You might be losing some parts of the audience by the "who is this aimed at" part.

**Comment by LukeMathWalker** [comment]
Thanks for pointing out these issues, I'll include fixes in the next errata release :+1: 

> Some food for thought: when I found this series for the first time (through arewewebyet) and read the introduction, I figured that this series is actually not for me. I have never built a backed system, nor do I plan to build a distributed system anytime soon, so I backed up. After couple of days I gave it a second shot and figured out that this is actually an amazing learning experience about how to build a well organized and reliable web app even for somebody, who has never ever built a web app before. So maybe think about it, change the wording a little bit. You might be losing some parts of the audience by the "who is this aimed at" part.

This is extremely valuable feedback - I set out to write a somewhat different book, but then I realised along the way that it is actually a good "introduction to backend" manual.
I plan to go back and revise the whole foreword section as well as the messaging on the website later down the line :100:

**Comment by LukeMathWalker** [comment]
The issue you mentioned has been fixed in the latest release :+1: 

I'll close the issue, but I am planning to incorporate your feedback in the foreword soon enough :)
