### ISSUE TITLE
Chap 3 Section 3.4.3 issues with cargo test

### ISSUE THREAD

**Issue by bvmcode** [LukeMathWalker/zero-to-production#221]
Here is my repo https://github.com/bvmcode/rust-email-newsletter

I am following along with the book through 3.4.3 and when running `cargo test` I am getting the error:

```
error[E0432]: unresolved import `newsletter::main`
 --> tests\health_check.rs:1:5
  |
1 | use newsletter::main;
  |     ^^^^^
```

Thanks in advance

**Comment by LukeMathWalker** [comment]
You cannot import a function defined in the binary (i.e. `main.rs`)—keep reading the chapter and it'll show you how to refactor to move it into the library!
