### ISSUE TITLE
Chapter 3.3: Link to Futures Explained in 200 Lines of Rust returns 404

### ISSUE THREAD

**Issue by okin** [LukeMathWalker/zero-to-production#229]
The link for _Futures Explained in 200 Lines of Rust_ leads to https://cfsamson.github.io/books-futures-explained/introduction.html which is currently returning a 404.

**Comment by joshuamegnauth54** [comment]
Its author is writing a longer book on async according to [this issue](https://github.com/cfsamson/examples-futures/issues/2).

**Comment by LukeMathWalker** [comment]
This has been fixed ✅
