### ISSUE TITLE
Chapter 03 pt1 test naming and result editing

### ISSUE THREAD

**Issue by gihrig** [LukeMathWalker/zero-to-production#23]
A couple minor points that only confuse those who geek out on details. ;-)

1. Section `2.2. Capturing Our Requirements As Tests` has a test named `subscribe_returns_a_200_for_valid_form_data`.
This also matches the [source](https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-03-part1/tests/health_check.rs#L72) in `tests/health_check.rs`. 
But the corresponding test result following the test source shown in the book has a test named `subscribe_accepts_valid_form_data`. There are four instances of this name in the text that should be changed to match the code.

2. I presume the test result shown in the book is edited to remove a lot of distracting `noise`. This is good, it's also rather different from what I see when I run `cargo test`. A simple suggestion that might avoid a few moments confusion, Label the test result something like:

`cargo test result (edited for clarity)`.

This is the rather noisy output I see from `cargo test`:

``` bash
$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.29s
     Running target/debug/deps/zero2prod-0ab5d8eae8ffd38e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/zero2prod-c6cfe04084471d4d

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/health_check-492d616831f44b24

running 3 tests
test health_check_works ... ok
test subscribe_returns_a_200_for_valid_form_data ... FAILED
test subscribe_returns_a_400_when_data_is_missing ... FAILED

failures:

---- subscribe_returns_a_200_for_valid_form_data stdout ----
thread 'subscribe_returns_a_200_for_valid_form_data' panicked at 'assertion failed: `(left == right)`
  left: `200`,
 right: `404`', tests/health_check.rs:57:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.

---- subscribe_returns_a_400_when_data_is_missing stdout ----
thread 'subscribe_returns_a_400_when_data_is_missing' panicked at 'assertion failed: `(left == right)`
  left: `400`,
 right: `404`: The API did not fail with 400 Bad Request when the payload was missing the email.', tests/health_check.rs:82:9
Panic in Arbiter thread.


failures:
    subscribe_returns_a_200_for_valid_form_data
    subscribe_returns_a_400_when_data_is_missing

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test health_check'
```

PS. I'm getting a lot of value from the book, it's much appreciated. Keep up the great work! :-)

**Comment by LukeMathWalker** [comment]
Thanks for reporting these issues :grin: 

1. is indeed an oversight, I'll try to fix it before the next release.  
On 2. - yes, I am editing the output to focus on what we are interested into (as well as making stuff fit within the margins :sweat_smile: ). I'll consider adding a note in the foreword/beginning - repeating here every single time seems excessive/noisy.

**Comment by LukeMathWalker** [comment]
Just released a new chapter + some corrections, including fixes for the issues you reported. Thanks again!
