### ISSUE TITLE
Binary name inconsistency

### ISSUE THREAD

**Issue by cedeerwe** [LukeMathWalker/zero-to-production#24]
In chapter 3 we defined the app name as `app`
![Screenshot from 2020-12-12 10-41-37](https://user-images.githubusercontent.com/11530208/101980577-a8210880-3c66-11eb-9b3f-e6a3d0936563.png)
However, the binary in chapter 5 is referred to as `zero2prod`. The guide itself therefore does not build.
![Screenshot from 2020-12-12 10-40-46](https://user-images.githubusercontent.com/11530208/101980580-a9eacc00-3c66-11eb-96bc-d54f45db2d97.png)
![Screenshot from 2020-12-12 10-40-34](https://user-images.githubusercontent.com/11530208/101980582-abb48f80-3c66-11eb-9895-41ff32ec4d3b.png)

Keep up the great work!

**Comment by LukeMathWalker** [comment]
Fixed and released, thank you!
