### ISSUE TITLE
5.4.2 databases version is not a supported

### ISSUE THREAD

**Issue by veenroid** [LukeMathWalker/zero-to-production#247]
In section 5.4.2, when updating the spec.yaml to include the database I receive the following when I attempt to update:

databases.version": "14" is not a supported database version.

Found this support message from a fellow Zero2Prod reader: [https://www.digitalocean.com/community/questions/error-validating-app-spec-field-databases-version-14-is-not-a-supported-database-version](https://www.digitalocean.com/community/questions/error-validating-app-spec-field-databases-version-14-is-not-a-supported-database-version)

Should the book be updated?

**Comment by LukeMathWalker** [comment]
This has been fixed by Digital Ocean: https://docs.digitalocean.com/release-notes/app-platform/#2024-05-01
