### ISSUE TITLE
Chapter 3 part 1 minor ommission

### ISSUE THREAD

**Issue by gihrig** [LukeMathWalker/zero-to-production#25]
In chapter 03 part 1 section 3.5.3 it would be helpful to have a notation in the code indicating the filename where the code is to be added:

```
//! src/configuration.rs <-- add this
...
impl DatabaseSettings {
...
```

PS. I'm really getting a lot out of Zero2Prod. This configuration feature has been on my list of things to put into my projects for some time, and here you just hand it to me complete. Lovin' it! 💯

**Comment by LukeMathWalker** [comment]
Good catch, fixed :grin:
