### ISSUE TITLE
Chapter 3  - CI Error communicating with database: Connection refused (os error 111)

### ISSUE THREAD

**Issue by bnzone** [LukeMathWalker/zero-to-production#255]
Hi, I've been trying to follow the book and fix the broken CI as it said in `Chapter 3.8.5.5 Updating Our CI Pipeline`

It said to grab the updated version of the GitHub Actions setup [here](https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-03-part1/.github/workflows/general.yml) which I did. But my CI fails every time on the same step with `error: error communicating with database: Connection refused (os error 111)`

https://github.com/bnzone/zero2prod/actions/runs/8442471032/job/23123940815#step:5:207

My workflow - https://github.com/bnzone/zero2prod/blob/main/.github/workflows/general.yml
My init_db script - https://github.com/bnzone/zero2prod/blob/main/scripts/init_db.sh

Am I missing some step?
Any help is appreciated 🙏🏻

**Comment by techotron** [comment]
You're at a similar place to me in the book. The [workflow file](https://github.com/bnzone/zero2prod/actions/runs/8442471032/workflow) used for that run isn't the same as the one you've updated.

It looks like you've copy/pasted the workflow file without changing the `on` key to reflect your repo so new workflows aren't running for you. In other words, try changing it to this:

```
...
on: [push, pull_request]
...
```

**Comment by bnzone** [comment]
@techotron 
Thank you so much for taking a look!  🙂

I updated the `on` key and the workflow `POSTGRES_DB` env variable to be "newsletter" and that worked!
