### ISSUE TITLE
Chapter 3 part1 missing import

### ISSUE THREAD

**Issue by gihrig** [LukeMathWalker/zero-to-production#26]
In chapter 03 part 1 section 3.5.3 the test is expected to pass at the end of the section, but it fails due to a missing import.

This import needs to be added to the last code block in the text for that section:

```rust
use zero2prod::configuration::get_configuration;
```

Then the test passes as expected. 😄

**Comment by LukeMathWalker** [comment]
Fixed and released, thank you!
