### ISSUE TITLE
Can't Run `sqlx migrate run` "permission denied"

### ISSUE THREAD

**Issue by currenthandle** [LukeMathWalker/zero-to-production#268]
# 5.4.6 One Last Push (zero2prod_20240903.pdf)

```sh
>  DATABASE_URL=MY-DIGITAL-OCEAN-DB-CONNECTION-STRING sqlx migrate run

error: while executing migrations: error returned from database: permission denied for schema public
```

[My spec.yaml](https://github.com/currenthandle/zero2prod/blob/chapter-5/spec.yaml), essentially the same as the book and your repo.

It seems that the `newsletter` db user doesn't have the permissions to run a migration against the postgres on DigitalOcean.

I'm also considered connecting to the db as `doadmin` or `root` but I don't have a password for `doadmin` or see anyway to (re)set it on Digital Ocean.

Any ideas why the `newsletter` db user doesn't have the permissions to run a migration and how to resolve? Thanks!

**Comment by maciejSzcz** [comment]
I faced the same issue while completing this chapter, and what worked for me is downgrading the database to postgresql 14 (I had to destroy the old database on DigitalOceans platform before reapplying the `spec.json`)

**Comment by currenthandle** [comment]
@maciejSzcz thanks for your reply. Yeah I tried the [same thing](https://github.com/currenthandle/zero2prod/blob/chapter-5/spec.yaml#L51) after referencing @LukeMathWalker 's [spec.yaml in the root-chapter-5 branch](https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-05/spec.yaml#L54). 

`spec.json`? Do you mean `spec.yaml`? Would you mind linking me to your repo?

**Comment by maciejSzcz** [comment]
@currenthandle You are obviously right, js brain took over. https://github.com/maciejSzcz/rs-mailer here is my repo, but your spec seems to be the same

**Comment by currenthandle** [comment]
Thanks! The only difference I see you and and the book have `region: fra` I have `region: sfo3`. Hard to believe this could be the issue, but maybe I should give Frankfurt a try :)

**Comment by currenthandle** [comment]
Ok I resolved the issue. I destroyed the project and started over.
First with `fra` and then again switched back to `sfo3`.

This time I didn't see this error when I ran the migration, for whatever reason:

```sh
>  DATABASE_URL=MY-DIGITAL-OCEAN-DB-CONNECTION-STRING sqlx migrate run

error: while executing migrations: error returned from database: permission denied for schema public
```

Instead is just hung forever. Same when I did `psql MY-DIGITAL-OCEAN-DB-CONNECTION-STRING`.

Per this footnote
<img width="590" alt="Screenshot 2024-10-30 at 8 31 24 AM" src="https://github.com/user-attachments/assets/5ce16086-8b4b-41f7-87b0-2be94de42072">

I unchecked this box in the Component > Database ("newsletter") settings and the migration worked. Then I rechecked the box to reenable the Trusted Sources protection.
<img width="932" alt="Screenshot 2024-10-30 at 8 31 41 AM" src="https://github.com/user-attachments/assets/52435112-377a-410d-ae0e-33dff5496915">

**Comment by 4ry1337** [comment]
For anyone stuck here, please read [this](https://docs.digitalocean.com/products/app-platform/how-to/manage-databases/#upgrade-dev-database-to-managed-database) doc carefully. Briefly, you can not migrate to dev database, you need to upgrade it to managed database.
And use `doadmin` connection string.
I hope this helped.
