### ISSUE TITLE
Chapter 3 part 1 - 3.6 typos and edits 

### ISSUE THREAD

**Issue by gihrig** [LukeMathWalker/zero-to-production#27]
The vary last sentence in `3.6. Persisting A New Subscriber` contains extra worlds:

"Let's see figure out how to get one."

Change to:

"Let's see how to get one."

**Comment by gihrig** [comment]
Another one:

Section 3.6.2, third paragraph under the code snippet begins:

"We can wrap our connection in an atomic reference counter point, an Arc:"

Rust [docs](https://doc.rust-lang.org/std/sync/struct.Arc.html) describe ARC as:

"A thread-safe reference-counting pointer. 'Arc' stands for 'Atomically Reference Counted'."

Suggestion:

Change as follows:
"We can wrap our connection in an atomic reference counter point, an Arc:"
"We can wrap our connection in an 'Atomiclly Reference Counted' pointer, an [Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html):"

Referencing the Rust docs for Arc.

**Comment by LukeMathWalker** [comment]
Fixed both :+1:
