### ISSUE TITLE
Chapter 3 part 1 - 3.6 More typos, edits and comments

### ISSUE THREAD

**Issue by gihrig** [LukeMathWalker/zero-to-production#28]
First I want to comment on your description of `web::Data` as an 'extractor' and how actix-web handles it at the end of section 3.6.3. The Data Extractor.

It's a clear enough description of new material, but being new to me, I wasn't quite sure what I would do with it beyond copy from your example. But when you mentioned that this feature is similar to _dependency injection_ that really made it click for me. Not so much the similarity of the underlying mechanism but just tying the discussion to some familiar terminology. This is the kind of material that really puts the polish on the book and makes it special.  
Well done! 💯

3.6.4. The INSERT query, typo:
1. The comment beginning:

```
// There is a bit of cerenomy here to get our hands on a &PgConnection.
```

_ceremony_ is misspelled.

2. The comment above ends with:

```
// We could have avoided the double Arc wrapping using .app_data()
// instead of .data() in src/startup.rs
```

It might be good to mention that this will be addressed later in this section.

3. In the last code snippet of the section, 

```rust
...
    .map_err(|e| {
        println!("Failed to execute query: {}", e);
...
```

The earlier version of this snippet uses `eprintln!()`, here it's changed to `println!()`. Intentional?

4. Just a thought: I notice in other Rust projects as well, various database-specific function calls and queries are scattered throughout the code base. Would it not make sense to package database-specific code in a separate module to allow for greater maintainability in the event a different database was employed for whatever reason? Is this just not thought about, too much trouble, has performance implications or other? Would love to hear your thoughts on this.

**Comment by LukeMathWalker** [comment]
On 3. - it was not intentional :sweat_smile: 

We'll get to cover 4. later in the book - putting database logic in a repository sub-crate and decoupling the domain from it using a trait requires a bit of ceremony which makes sense once you have a bunch of queries and it starts to get hairy. As other things in the book I prefer to take things a bit further before refactoring to show why it makes sense to bother doing it in the first place :grin:

**Comment by LukeMathWalker** [comment]
Fixed and released :rocket:
