### ISSUE TITLE
 Chapter 3 part 1 - 3.7 edits

### ISSUE THREAD

**Issue by gihrig** [LukeMathWalker/zero-to-production#29]
3.7. Updating Our Tests

1. First paragraph following the first code snippet, change:

'...to perform our SELECT query, it makes to generalise a bit spawn_app: instead of returning a raw String,...'

to:

'...to perform our SELECT query, it makes sense to generalise spawn_app a bit: Instead of returning a raw String,...'

2. Farther down in the section there's an extra word, change:

'The moment of the truth has finally come:...'

to:

'The moment of truth has finally come:...'

3.7.1. Test Isolation

1. In the first code block, Uuid should be imported

`use uuid::Uuid;`

2. In the last code block change:

`use sqlx::Executor;`

to:

`use sqlx::{Connection, Executor, PgConnection, PgPool};`

add:

`use zero2prod::configuration::{get_configuration, DatabaseSettings};`

---

I really enjoyed Chapter 3 - Got a lot out of it!

Unfortunately, I need to do some 'paying work' before I dive into chapter 4, so I may be absent for a while, I'm really anticipating the continued journey.

**Comment by LukeMathWalker** [comment]
All fixed :ok_hand: 
Glad you are enjoying it, keen to have your feedback on the remaining chapters :grin:
