### ISSUE TITLE
Chapter 3.5 a few more issues

### ISSUE THREAD

**Issue by gihrig** [LukeMathWalker/zero-to-production#31]
I'm giving this chapter a second reading (while applying the material to a production project) ;-)

Here's a few minor (some debatable) issues I noticed:

1. 3.1. Choosing A Database

    it is much easier to design yourself in a corner <-- design yourself into a corner

2. 3.4.2.3. Adding A Migration

    our mailing list would have to incredibly popular <-- have to _be_ incredibly popular

3. 3.4.2.4. Running Migrations

	if Postgres is not spinned up by our script. <-- not spun up by our script
	
4. 3.5.1. Sqlx Features Flags <--- 3.5.1. Sqlx Feature Flags

	[Crates.io](https://crates.io/crates/sqlx) actually lists "Cargo Feature Flags", but that feels wrong. I would stick with Sqlx Feature Flags.

5. 3.5.2.2. Reading A Configuration File

	Do you think it would be off-topic to mention here that production 
	passwords should not be included in files committed to the repository?

6. 3.6.1. Application State In Actix-web

	The first code listing is missing the comment `//! src/startup.rs`

7. 3.6.4. The INSERT query

	we designed ourselves in a corner <--- we designed ourselves into a corner

8. 3.7. Updating Our Tests

	perform our SELECT query, it makes to generalise spawn_app a bit <--- it make sense to generalise

**Comment by LukeMathWalker** [comment]
Addressed them all in the upcoming release, thank you!
