### ISSUE TITLE
Running the health check test with tokio 1.0.1 panics

### ISSUE THREAD

**Issue by rihardsk** [LukeMathWalker/zero-to-production#32]
This isn't really an issue with the guide itself but maybe this should be addressed as it's, i think, a common thing people following along might run into.

Running `cargo test` on the `root-chapter-03-part0` at 447fdbfa96dbd11884b68ee93c0c6e23c96ade22 works fine, but if i use tokio 1.0.1 instead of 0.2.22 like so:
```diff
diff --git a/Cargo.toml b/Cargo.toml
index b242cf2..131708e 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -15,7 +15,7 @@ name = "zero2prod"
 [dependencies]
 actix-web = "3.0.0"
 actix-rt = "1.1.1"
-tokio = "0.2.22"
+tokio = { version = "1.0.1", features = ["full"] }
 
 [dev-dependencies]
 reqwest = "0.10.7"
```
i get a panic when running `cargo test`
```
running 1 test
test health_check_works ... FAILED

failures:

---- health_check_works stdout ----
thread 'health_check_works' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /home/rihards/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/task/spawn.rs:131:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
```

Still trying to figure out how to solve this myself and whether or not this is something to be reported upstream.

EDIT: checked that the same thing happens with tokio 0.3.

**Comment by LukeMathWalker** [comment]
This is known and unsolvable until all the dependencies of our project upgrade to `tokio` 1.x.x - I am keeping an eye on everything we need and I'll update the book to use the latest `tokio` when possible :)

**Comment by LukeMathWalker** [comment]
The bare minimum we need is https://github.com/actix/actix-web/pull/1813 to be merged and released 😁

**Comment by abbudao** [comment]
I believe we are having the very same issue with `reqwest` 0.11 and above. Maybe, for now, you should add a specific version to your instructions as you did with Tokio?
```rust
// We brought `reqwest` in as a _development_ dependency
// to perform HTTP requests against our application.
// Either add it manually under [dev-dependencies] in Cargo.toml
// or run `cargo add reqwest --dev --vers 0.10.7`
```

**Comment by LukeMathWalker** [comment]
I have updated the comment - thanks @abbudao!

**Comment by LukeMathWalker** [comment]
Finally fixed 😁 
The whole book in on tokio 1.x.x now!
