### ISSUE TITLE
Chapter 7 JSON body error.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#36]
In [JSON body](https://www.lpalmieri.com/posts/how-to-write-a-rest-client-in-rust-with-reqwest-and-wiremock/#json-body) `from: self.sender.to_owned()` should be `from: self.sender_as_ref().to_owned()`.

Credit to [/u/Azdle](https://reddit.com/user/Azdle) on [/r/rust](https://old.reddit.com/r/rust/comments/kza6ay/zero_to_production_in_rust_part_70_how_to_write_a/gjool0z/) for the fix.

**Comment by LukeMathWalker** [comment]
Thanks, fixed 😁
