### ISSUE TITLE
Missing use statement in Body.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#37]
In [Body](https://www.lpalmieri.com/posts/how-to-write-a-rest-client-in-rust-with-reqwest-and-wiremock/#body) `use wiremock::{Mock, MockServer, ResponseTemplate}` needs to read `use wiremock::{Mock, MockServer, Request, ResponseTemplate};`

**Comment by LukeMathWalker** [comment]
Fixed now!
