### ISSUE TITLE
It would be healpful mentioning curl post syntax earlier as its not so obvious.

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#38]
4.4.3 Logs Must Be Easy To Correlate

It would be useful if the curl for adding a subscriberl was added earlier as its not very obvious
and it would make it easier to try out the code.

```
curl -i -X POST -d 'email=thomas_mann@hotmail.comname=Tom' \
    http://127.0.0.1:8000/subscriptions
```

**Comment by LukeMathWalker** [comment]
Done in the latest release, thank you!
