### ISSUE TITLE
Looks like someone has allready written rust bunyan

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#39]
4.5.11 Logs For Integration tests

It looks like someone has already created a Rust version of bunyan.
```
cargo install bunyan
```

**Comment by LukeMathWalker** [comment]
> It looks like someone has already created a Rust version of bunyan.

That would be me 😂 Not sure I want to evangelise it yet via the book.

**Comment by LukeMathWalker** [comment]
I added a small comment about it for people who really don't want to touch npm.
