### ISSUE TITLE
Clippy recomended using &[] rather then vec![] in for loop

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#41]
6.9 Unit tests

Clippy suggested using &[] rather then using a vec![] in for loop in test code.

https://rust-lang.github.io/rust-clippy/master/index.html#useless_vec

```rust
for name in &['/', '(', ')', '"', '<', '>', '\\', '{', '}'] {
```

**Comment by LukeMathWalker** [comment]
Fixed in the latest release, thank you!
