### ISSUE TITLE
Chapter 3.5, Page 31 has a typo

### ISSUE THREAD

**Issue by shubhamkumar13** [LukeMathWalker/zero-to-production#43]
```rs
use zero2prod::run;
#[actix_rt::main]
async fn main() -> std::io::Result<()> {
// Bubble up the io::Error if we failed to bind the address
// Otherwise call .await on our Server
run()?.await
}
```

the above code snippet should be `run().await` instead of `run()?.await`

**Comment by LukeMathWalker** [comment]
Hey!
Looking at the signature of the `run` function 

```rust
pub fn run() -> Result<Server, std::io::Error> { }
```

that seems correct to me 🤔

**Comment by shubhamkumar13** [comment]
I don't exactly know why but I was getting this error -> https://gist.github.com/shubhamkumar13/9ef793f0ae68e2cefca379555825396f

**Comment by LukeMathWalker** [comment]
What is the signature of your `run` function? Have you removed `async` from it?

**Comment by shubhamkumar13** [comment]
```rs
use zero2prod::run;
#[actix_rt::main]
async fn main() -> std::io::Result<()> {
// Bubble up the io::Error if we failed to bind the address
// Otherwise call .await on our Server
run()?.await
}
```
this is what my function looked like, also I'm sorry for being late but I tried to recreate the error and it seems to pass. It seems to be an oversight on my part, sorry for that.

**Comment by shubhamkumar13** [comment]
I'll close the issue
