### ISSUE TITLE
Typos in #7.1

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#48]
Instead of creating a bunch of small issues for typos, I'll list them all as separate comments on this one issue. 

In the [Sharing Startup Logic](https://www.lpalmieri.com/posts/skeleton-and-principles-for-a-maintainable-test-suite/#sharing-startup-logic) code block it identifies the wrong file:
```
//! tests/app/helpers.rs
```
should be:
```
//! tests/api/helpers.rs
```

**Comment by cldershem** [comment]
Another bug in the same section, "Extracting Our Startup Code", `src/startup.rs` requires an extra `use` statement that is missing, `use crate::configuration::Settings`.

**Comment by cldershem** [comment]
In [Chapter #6 - Unit Tests](https://www.lpalmieri.com/posts/2020-12-11-zero-to-production-6-domain-modelling/#9-unit-tests) we begin writing all of our tests in `./tests` (that is a directory named, "tests" in the root of our project. In Chapter #7.1 the directory is referred to as both "./test" and "./tests". `cargo` is apparently smart enough to pick up on this, but I am not :smiley: . I would suggest picking one convention and sticking to it throughout the book.

**Comment by cldershem** [comment]
In the section step where one is to, "Add three empty files - tests/api/helpers.rs, tests/api/health_check.rs and tests/api/subscriptions.rs", it explicitly states that `configure_database` isn't public, but it doesn't point out that `spawn_app` is now public. This is pretty easy to overlook.

**Comment by cldershem** [comment]
In "Testing Hooks in Our Startup Logic" `zero2prod::startup::get_connection_pool` is imported, but we haven't written it yet.

**Comment by cldershem** [comment]
In the section starting with "Let's deal with the connection pool first:" the code requires `use crate::configuration::DatabaseSettings;`

**Comment by cldershem** [comment]
`tests/api/helpers.rs` requires `use zero2prod::startup::Application;` in the last example before "Build an API Client".

**Comment by cldershem** [comment]
In the last set of examples before "Build An API Client" in `src/startup.rs`:

```
    let port = listener.local_addr().unwrap().port;
```
should be:
```
    // `port` is a method, not a field
    let port = listener.local_addr().unwrap().port();
```

**Comment by LukeMathWalker** [comment]
Thanks for the detailed feedback - they should all be fixed in the latest release 😁
