### ISSUE TITLE
Ch 5.3.8.2 Dockerfile rust image correction

### ISSUE THREAD

**Issue by dalrrard** [LukeMathWalker/zero-to-production#50]
In the 3rd build stage of the dockerfile, `builder`, the rust image is pinned to version 1.49. This causes the `builder` stage to re-compile all dependencies since `lukemathwalker/cargo-chef` image uses `latest` which is now at version 1.50.

**Comment by LukeMathWalker** [comment]
Good catch! I'll amend 😁

**Comment by LukeMathWalker** [comment]
Done!
