### ISSUE TITLE
Chapter 7.3: mention limits for open file descriptors on Linux and how to change them (ulimit)

### ISSUE THREAD

**Issue by SuperFluffy** [LukeMathWalker/zero-to-production#51]
When combining all integration tests into one binary as done in Chapter 7.3, one can relatively quickly run into errors akin to this:

```bash
{"v":0,"name":"test","msg":"Can not initialize stream handler for Term err: Too many open files (os error 24)",
"level":50,"hostname":"blackie","pid":39982,"time":"2021-02-19T12:43:53.978735862+00:00",
"log.target":"actix_server::signals","log.line":58,"log.module_path":"actix_server::signals",
"log.file":"/home/janis/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/signals.rs"}

thread 'actix-rt:worker:288' panicked at 'Can not create Runtime: Os { code: 24, kind: Other,
message: "Too many open files" }',
/home/janis/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:115:45

thread 'login::login_returns_401_with_missing_username_or_password' panicked at
'Failed to execute request.: reqwest::Error { kind: Request, url: Url { scheme: "http",
host: Some(Ipv4(127.0.0.1)), port: Some(36349), path: "/user/register", query: None, fragment: None },
source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused,
message: "Connection refused" })) }', tests/api/login.rs:31:20
```

The reason that this happens is that instead of having several binaries, each running as their own process, we now have one process that attempts to open file descriptors (which includes sockets). On Linux, the limit for the maximum number of file descriptors that one process is allowed to have open at the same time is 1024 (your individual distribution can deviate from this number and set their own limit):

```
❯ ulimit -a
Maximum size of core files created                           (kB, -c) unlimited
Maximum size of a process’s data segment                     (kB, -d) unlimited
Maximum size of files created by the shell                   (kB, -f) unlimited
Maximum size that may be locked into memory                  (kB, -l) 64
Maximum resident set size                                    (kB, -m) unlimited
Maximum number of open file descriptors                          (-n) 1024
Maximum stack size                                           (kB, -s) 8192
Maximum amount of cpu time in seconds                   (seconds, -t) unlimited
Maximum number of processes available to a single user           (-u) 240647
Maximum amount of virtual memory available to the shell      (kB, -v) unlimited
```

You can change the limit with `ulimit -n <number>`. For example, `ulimit -n 8192` allows my tests to pass.

**Comment by SuperFluffy** [comment]
If somebody has suggestions on how to fix this programmatically, I would be very happy to hear it. When running CI I suppose one could have it set the ulimit. But I am wondering if it's possible to either have Cargo set the ulimit before running tests, or by somehow pointing out to the user that they have to change the limits manually before running tests should a panic occur.

**Comment by LukeMathWalker** [comment]
You could probably abuse a build script with an arch cfg to raise `ulimit` before execution 🤔 
I added a paragraph about it to the latest release, thanks for reporting!

**Comment by adamwoolhether** [comment]
Is there really no way to control the tests from within rust itself?

**Comment by brunojppb** [comment]
I've recently ran into this exact same issue on MacOS Ventura (13.3.1). Running `ulimit -a` has given me the following output:

```shell
ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       5333
-n: file descriptors                256
```

Executing `ulimit -n 8192` did the trick.

Great book btw, @LukeMathWalker. Really enjoying the read so far! 👏
