### ISSUE TITLE
3.8.5.1 Sqlx Feature Flags Code Snippet Syntax Error

### ISSUE THREAD

**Issue by mdtro** [LukeMathWalker/zero-to-production#52]
First off, thank you for writing Zero To Production in Rust! I'm really enjoying your book and am looking forward to working through what's available now and the upcoming chapters. 

In Chapter 3 (specifically 3.8.5.1), there's a code snippet there to update the _Cargo.toml_ file to include `sqlx` with some feature flags. The example is missing `version = "0.5.1"`  and `features = [` for the beginning of the feature flag list.

``` toml
# Using table-like toml syntax to avoid a super-long line!
[dependences.sqlx]                              
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]
```

Here's what I ended up with that worked:
``` toml
[dependencies.sqlx]
version = "0.5.1"
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]
```

In your Chapter 3, Part 1 snapshot of the Cargo.toml file, you have:
```
sqlx = { version = "0.5.1", default-features = false, features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
```

I didn't disable the default features, so we will see if that comes back to haunt me as I move along through the book. 😄

**Comment by LukeMathWalker** [comment]
Thanks for reporting - I fixed it in the latest release 😁 

Disabling the default features should mostly be a way to reduce compilation team 😁
