### ISSUE TITLE
Chapter 4.3 - typo in curl https://<...>

### ISSUE THREAD

**Issue by yngtodd** [LukeMathWalker/zero-to-production#53]
In section `4.3`, there is a small typo in the `curl` command: 

<img width="625" alt="section4 3_curl" src="https://user-images.githubusercontent.com/16848331/108642630-769d9800-7474-11eb-8684-83f03982efe6.png">

Using `https://` will result in 

```
❯ curl https://127.0.0.1:8000/health_check
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Dropping the `s` in `https://` will sort it!

```
❯ curl http://127.0.0.1:8000/health_check
~
```

Loving the book!

**Comment by LukeMathWalker** [comment]
Thanks for reporting - I fixed it in the latest release 😁
