### ISSUE TITLE
Chapter 1: Rust format defaults

### ISSUE THREAD

**Issue by bbros-dev** [LukeMathWalker/zero-to-production#57]
I found this a handy thing to add Rust format defaults to the project `rustfmt.toml`

```bash
rustfmt --print-config default rustfmt.toml
```

Not sure where this would be best placed.

**Comment by LukeMathWalker** [comment]
What is the value of having a `rustfmt.toml` if you are not customising the configuration though? 🤔

**Comment by gihrig** [comment]
Just adding to the conversation...

Before switching from PHP, Java, JS to Rust as my main language about a year ago, I was into tweaking format style to the nth degree. Not having that ability in Rust (or not knowing about it), I have accepted the value of all-inclusive standards for trivial things, like style, and accepted that I have plenty to learn about Rust. I don't need to spend time on trivial details the compiler will dispense with anyway.

The hardest things for me were required semicolons everywhere, accept return values, and 4 space indents, thankfully it's 4 spaces not tabs ;-).

Over the past year plus, I remain sufficiently challenged by Rust details, that this trivia just doesn't register any more. Having a few more mental cpu cycles to spend on the important stuff has become much appreciated.

I have not missed `.eslintignore`, `.eslingt.js`, `.editorconfig', etc., not much anyway.

**Comment by bbros-dev** [comment]
My understanding is 02P is aimed at people new to rust, and at least people who are going through the Rust book or Rust by example

> What is the value of having a rustfmt.toml if you are not customising the configuration though?

This addresses the premise behind your question.
 - How do you know the extent to which rustfmt defaults can be configured?
 - How do you know what rustfmt imposes? This cuts out a lot of experimentation - just scanning that list gives good overview.
  
@gihrig makes a valid point - leave it alone.  However, some orgs have coding styles and standard that are entrenched (i.e. strong resistance to change).  It helps to let people know to what extent the `rustfmt` can accommodate their existing conventions or existing requirements. Or do they need to look for another crate?

**Comment by LukeMathWalker** [comment]
>     * How do you know (with minimal effort) the extent to which rustfmt defaults can be configured?
> 
>     * How do you know (with minimal effort) what rustfmt imposes? This cuts out a lot of experimentation - just scanning that list gives good overview.
> 
> 
> @gihrig makes a valid point - leave it alone. However, some orgs have coding styles and standard that are entrenched (i.e. strong resistance to change). It helps to let people know to what extent the `rustfmt` can accommodate their existing conventions or existing requirements. Or do they need to look for another crate?

I 100% agree that people should know that `rustfmt` is customisable - that's why in that very section we link to https://github.com/rust-lang/rustfmt#configuring-rustfmt

On the flip side, @gihrig is right: the Rust community encourages to stick with the default configuration and avoid tweaking it.
Adding a default `rustfmt.toml` file gives the impression that each Rust project should have one as a best practice, which is not the case.
