### ISSUE TITLE
Chapter 3.3.1: Graceful termination of actix webserver (blocking cargo run)

### ISSUE THREAD

**Issue by bbros-dev** [LukeMathWalker/zero-to-production#59]
After `curl ...` returns `"Hello World!", would be nice to know how to properly cleanup the web server we have running.
Ctl+c seemed to work and I couldn't see any orphaned processes, but then again I didn't check to see what they might be called - my bad.  But if there is a blessed shutdown mechanism, here is a good place to introduce it.

**Comment by LukeMathWalker** [comment]
Good shout, I added a quick sentence in the latest release 😁
