### ISSUE TITLE
Configuration secrets and undo migrations

### ISSUE THREAD

**Issue by migueloller** [LukeMathWalker/zero-to-production#6]
@LukeMathWalker, thanks for writing this great book!

I’ve got two questions:
- What are your thoughts on undo migrations? Is it something that you plan to add? How are migration workflows usually dealt with in cloud-native environments, specially rollbacks? For example, in Kubernetes, I’ve used Helm hooks to run migration jobs when deploying but I haven’t found a good solution for rollbacks.
- What’s the plan for configuration secrets like a database password? Will they just be stored in the repo encrypted or perhaps there will be an overrides files not checked into version control? How will this interact with the fact that there are multiple sources of truth for config values (i.e., .env and configuration.yaml)? Are there plans to get rid of these multiple sources of truth? It does feel a bit dirty/problematic.

Thanks!

**Comment by LukeMathWalker** [comment]
Hey!

- There are two school of thoughts on database migrations: one in favour of rollbacks, one that believe rollbacks do not exist - i.e. a rollback is just another migration. I am pretty agnostic on the subject, so I generally adapt to the tool I am using: `sqlx` follows the second set of principles, so we will not have rollbacks.
- In all the environments I worked into secrets were generally managed separately and injected at runtime/booting time either via configuration files or environment files (e.g. using the `secretKeyRef` in Kubenertes). We will see how to blend those into our `Settings` struct using `config` when we will cover our deployment pipeline.
Right now we don't have multiple sources of configuration - `.env` is completely ignored by our `Settings` struct, it's only used by `sqlx` at compile-time to perform checks on the soundness of our queries. It would feel cleaner if we managed to get it out of `configuration.yaml` for `sqlx` as well, but I wouldn't sweat it too much tbh.

**Comment by migueloller** [comment]
Thanks for the prompt reply!

- Ah, that makes a lot of sense. I had only been aware of the first school of thought. Do you know if there are any resources, maybe on `sqlx`’s docs, that explain their rationale for going in this direction?
- Cool, I thought we would get there eventually once multiple environments were considered for configuration. Looking forward to it! As for reading it from the config file, yeah, it’s definitely a nice-to-have.

**Comment by LukeMathWalker** [comment]
You can start having a look here: https://github.com/rust-db/refinery#rollback

**Comment by migueloller** [comment]
Thanks!
