### ISSUE TITLE
5.3.7 Database connectivity panics at PgPool::connect

### ISSUE THREAD

**Issue by sjud** [LukeMathWalker/zero-to-production#62]
I've followed along and am now receiving an error when running the docker container. Also, thanks so much for writing the book. It's exactly what I was looking for and it's the perfect step in my beginner->intermediate journey.

`#9 194.2 thread 'main' panicked at '
#9 194.2 failed to connect to Postgres URL postgres://postgres:password@localhost:5432/newsletter
#9 194.2 : Io(Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })', src/main.rs:16:10
#9 194.2 stack backtrace:
...
`

**Comment by LukeMathWalker** [comment]
Uh, they fixed it 😁 
I'll update that section in the next release then - just connect lazily for now.

**Comment by LukeMathWalker** [comment]
Mmm I wasn't actually able to reproduce this. Looking at `sqlx`'s source code it still looks like they "swallow" a connection refused error https://github.com/launchbadge/sqlx/blob/edcc91c9f282df92def0b7655a000aa5fb798253/sqlx-core/src/pool/inner.rs#L250

What platform are you using?

**Comment by sjud** [comment]
Hmm, that's interesting. I'm using MacOS 11.2

**Comment by sjud** [comment]
Connecting lazily works, so I'm going to close this since it seems like it's more of a sqlx issue than a zero to production one.

**Comment by samuelvanderwaal** [comment]
I'm getting this same error. How do I connect lazily with `sqlx`?
