### ISSUE TITLE
Chapter 3.5: For `spawn_app()` an `.await;` is required

### ISSUE THREAD

**Issue by bbros-dev** [LukeMathWalker/zero-to-production#63]
Its been a long day so may have got some part wrong.... but am finding that the `spawn_app()` requires `.await;` on pg 32.

Without it:

```bash 
$ cargo test --verbose --test healthy_check

running 1 test
test health_check_works ... FAILED

failures:

---- health_check_works stdout ----
thread 'health_check_works' panicked at 'Failed to execute request.: reqwest::Error { kind: Request, url: Url { scheme: "http", username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8000), path: "/health_check", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', tests/healthy_check.rs:18:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    health_check_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: test failed, to rerun pass '--test healthy_check'

```

The `spawn_app` is:

```rust
async fn spawn_app() {
    let server = zero2prod::run().expect("Failed to bind address");
    let _ = tokio::spawn(server);
}
```

**Comment by bbros-dev** [comment]
Ditto on page 36.

**Comment by bbros-dev** [comment]
Okay, hitting the same errors of page 38.

**Comment by bbros-dev** [comment]
Confirmed: [Issue with the book text](https://github.com/LukeMathWalker/zero-to-production/blob/f0d346f4ad91a1122b4678e5218d11b32a5995a4/tests/api/health_check.rs#L6)

**Comment by LukeMathWalker** [comment]
I was just looking into this - can you post both the code you have in `spawn_app` and the code in your test?
The snapshot you linked refers to the latest chapter.
If you look at that [very same file at the end of the first half of chapter 3](https://github.com/LukeMathWalker/zero-to-production/blob/root-chapter-03-part0/tests/health_check.rs), `spawn_app` is synchronous.

**Comment by bbros-dev** [comment]
I hadn't spotted the various branches.  Will reopen if What I have conflicts with the branch content.  Closing until then.
