### ISSUE TITLE
Breaking change of actix-http lib makes all code in book impossible

### ISSUE THREAD

**Issue by hazaard** [LukeMathWalker/zero-to-production#67]
Hey Luke! I'm following examples in the beginning of the book and they don't work due to breaking change in actix-http library v3.0.0-beta.3.
actix-web v4.0.0-beta.3 couldn't be compiled.

Way to reproduce:
- checkout your own code (Chapter 3, part 0 is okay)
- delete Cargo.lock
- run cargo build.

How I managed to fix:
- just put actix-http = "=3.0.0-beta.2" into Cargo.toml explicitly.

I understand it's an issue of actix-web, not of the book, but you ensist on using of unstable version of actix-web so it will be better at least to inform your readers about possible issues.

p.s: Using stable version of actix-web didn't work for me either - there is to way to spawn server with tokio using your code for test cases.

Regards,
Artem

**Comment by LukeMathWalker** [comment]
Hey!

I am sorry you had a rough time with `actix-web`'s beta - it was the least evil path forward to get everything on `tokio` `1.x.x`.
I'll amend the installation instructions in the next release to account for this issue.

**Comment by hazaard** [comment]
Hey there! Good news. Actix-web beta.3 is compiling again so problem is not relevant anymore. Still worth mentioning in the book.
