### ISSUE TITLE
Code snippets are really hard to read in BW

### ISSUE THREAD

**Issue by dfioravanti** [LukeMathWalker/zero-to-production#69]
First at all, thanks for the amazing book.

Would it be possible to change the background colour of the code snippets in the pdf? Having a pitch black background makes it really hard to read on a BW ereader. I was thinking something like a dark gray or something similar would be much easier to read.

My workflow is that I read a chapter on the ereader and then I go back and implement everything. In the end it is not a huge problem but it would make my life, and other people I would assume, much easier. I would add that I find it a bit hard to read even on screen but there it is absolutely tolerable.

**Comment by LukeMathWalker** [comment]
Next release will include a light theme version 😁
