### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by dfioravanti** [LukeMathWalker/zero-to-production#70]
I found the following typos when reading the last version of the pdf

1. In the last code snippet on page 30 there is a `Responder` missing in the import list. It should be 
`use actix_web::{web, App, HttpResponse, HttpServer, Responder};`
instead of 
`use actix_web::{web, App, HttpResponse, HttpServer};`
2. The box at end of page page 43 is aligned with the subsubsection header. My guess is that there is a `/newline` missing

**Comment by LukeMathWalker** [comment]
On page 30, are you referring to this code snippet?

```rust
use actix_web::{web, App, HttpResponse, HttpServer};

async fn health_check() -> HttpResponse {
    HttpResponse::Ok().finish()
}

// We need to mark `run` as public.
// It is no longer a binary entrypoint, therefore we can mark it as async
// without having to use any proc-macro incantation.
pub async fn run() -> std::io::Result<()> {
    HttpServer::new(|| {
            App::new()
                .route("/health_check", web::get().to(health_check))
        })
        .bind("127.0.0.1:8000")?
        .run()
        .await
}
```

Good catch on the box, thank you!

**Comment by dfioravanti** [comment]
> On page 30, are you referring to this code snippet?

Yes. I should have wrote page 30/31 to make it more clear =)

**Comment by LukeMathWalker** [comment]
If I try to compile that snippet, I don't get any errors 🤔 Why do you think `Responder` is necessary?

**Comment by dfioravanti** [comment]
I cannot really remember why I thought it was necessary. If I remember correctly it is because when one breaks up the main in the submodules one ends up needing `Responder` in that file too. But I am not sure. I agree that in the snippet is not strictly speaking necessary. In the end it is nothing super important

**Comment by LukeMathWalker** [comment]
I might have been because, originally, `health_check` returned `impl Responder`?
Anyway, I'll close this 👍🏼
