### ISSUE TITLE
Tracing's log flag is not on by default

### ISSUE THREAD

**Issue by dfioravanti** [LukeMathWalker/zero-to-production#72]
On page 83 it is written `This works thanks to tracing’s log feature flag, which is enabled by default.`. This does not appear to be true any more. I was a bit confused because no log message was produced with the code as presented in the book. I added `features = ["log"]` to cargo.toml and now it works as intended

**Comment by LukeMathWalker** [comment]
That's an annoying change, thanks for getting to the bottom of it!

**Comment by LukeMathWalker** [comment]
Fixed in the latest release, thanks!
