### ISSUE TITLE
A way to see which version of the epub you are looking at.

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#73]
Is it possible to have a changelog for the book with the version in the book.  I have been downloading it as you update but there is no easy way to see what changed and what the current version is.  Sorry if this is somewhere and I have just missed it.

**Comment by LukeMathWalker** [comment]
You are correct - there is currently no way to know which version of the book you are looking at. I'll consider adding a release timestamp to the filename going forward.

In terms of changelog: most changes are rephrasing and typo fixes. 
Major changes (e.g. upgrading `tokio` or `actix-web`) are always announced/mentioned in the book newsletter.

**Comment by emiddleton** [comment]
OK, I was running through the code in the book start to finish and so was interested if upgrading to tokio had resulted in changes to code I had already gone through.

**Comment by LukeMathWalker** [comment]
I see - I'd suggest to refer to the code repository here to understand at a glance what changed.
Code related to a previous chapter lives in its own branch and you can browse the commit history to find out what changed after the initial release.

The latest release of the book include a trailing timestamp to help readers to understand if they have the latest.
