### ISSUE TITLE
Pg 210 Compiler error when using code example

### ISSUE THREAD

**Issue by sjud** [LukeMathWalker/zero-to-production#77]
Hello!
I hope I'm being more helpful than annoying by opening these issues everywhere. Using the code on page 210 
```
let html_link = get_link(&body["HtmlBody"].as_str().unwrap());
let text_link = get_link(&body["TextBody"].as_str().unwrap());
```
I get the error: 

error[E0277]: the type `str` cannot be indexed by `&str`
   --> tests/api/subscriptions.rs:128:31
    |
128 |     let text_link = get_link(&body["TextBody"].as_str().unwrap());
    |                               ^^^^^^^^^^^^^^^^ string indices are ranges of `usize`
    |
    = help: the trait `SliceIndex<str>` is not implemented for `&str`
    = note: required because of the requirements on the impl of `Index<&str>` for `str`

I fixed this error by writing
```
    let html_body_index = body.find("HtmlBody").unwrap();
    let text_body_index =  body.find("TextBody").unwrap();
    let html_link = get_link(&body[html_body_index..text_body_index]);
    let text_link = get_link(&body[text_body_index..]);
```
Although I can't guarantee that it gets the intended logic correct, it does get me to the test failure message described on page 11.
Edit: I needed to change the string formats to use '' inside of "" but other than that the test passed.

**Comment by emiddleton** [comment]
I think I have the correct answer for this.  The body needs to be parse into a serde_json Value.

```rust
//! tests/api/subscriptions.rs
// [...]
use serde_json::Value;

#[actix_rt::test]
async fn subscribe_sends_a_confirmation_email_with_a_link() {
    // [...]

    // Parse the body as a string, starting from raw bytes
    let body: Value =
        serde_json::from_str(std::str::from_utf8(&email_request.body).unwrap()).unwrap();
```

**Comment by sjud** [comment]
Yes! I finished the chapter and find that out, although that information is introduced a couple pages later. Are these compile errors in the code examples teaching tools or mistakes? I've definitely learnt a lot by debugging them but I just wanted to put an issue here in case the intention was that they work immediately.

**Comment by emiddleton** [comment]
I don't know @LukeMathWalker would have to answer that.  Are you just being a zen master and pretending to make mistakes so we learn ;)

**Comment by LukeMathWalker** [comment]
Ahah I'll have to check!
I go through all the issues once a week, so I'll come around to look into this one (and others) over this weekend :)

**Comment by LukeMathWalker** [comment]
@emiddleton was indeed correct - there a line missing parsing the bytes to JSON 😅
