### ISSUE TITLE
For code refered to in error boxes line numbers would be helpful.

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#78]
I was looking at the first error box in `7.7.2.1 Red Test` and it refers to line `tests/api/subscriptions.rs:72:9` but because there is no line numbers its not clear what line that actually refers to.

**Comment by LukeMathWalker** [comment]
It's unfortunate, but keeping line numbers in sync with the repository (or just self-consistent within the text itself) is basically impossible.
