### ISSUE TITLE
Code uses updated version of wiremock

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#79]
It looks like you updated the version of wiremock from 0.4.9 to a later version that includes the `received_requests` method but didn't update the reference in `7.2.3.1 HTTP Mocking With wiremock`.  I ran into issues in `7.7.2.1 Red Test` which uses `received_requsts`

**Comment by LukeMathWalker** [comment]
I had even taken a note to update the past chapter.. 😅 Thank you for raising this!
