### ISSUE TITLE
Typo in file paths

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#81]
Under `7.7.4.1` the third code block lists the test file path as `tests/subscriptions_confirm.rs` but it should be `tests/api/subscriptions_confirm.rs`

Under `7.7.4.2` the first code block lists the module file path as `src/routes/lib.rs` but it should be `src/routes/mod.rs`

**Comment by LukeMathWalker** [comment]
Thank you 🙇🏼‍♂️
