### ISSUE TITLE
Minor Issues on Chapter 7.2

### ISSUE THREAD

**Issue by Darrenmeehan** [LukeMathWalker/zero-to-production#85]
Hi there, I'm really enjoying this book. The experience of being guided through various problems, with compiler issues and refactors scripted is awesome! It's like we're pairing on this application, it's an amazing format. It's a great way to learn, I find it a quite productive way to explore the Rust ecosystem. Thanks so much for all your hard work!

I came across two minor issues on Chapter 7 which I thought I better share.

This first issue is introduced on page 171. (Interestingly `cargo` displays this issue twice for me, it's on my list of things to explore further.)

```rust
error[E0599]: the method `to_owned` exists for struct `SubscriberEmail`, but its trait bounds were not satisfied
   |
  ::: src/domain/subscriber_email.rs:4:1
   |
4  | pub struct SubscriberEmail(String);
   | -----------------------------------
   | |
   | method `to_owned` not found for this
   | doesn't satisfy `SubscriberEmail: Clone`
   | doesn't satisfy `SubscriberEmail: ToOwned`
  --> src/email_client.rs:29:31
   |
29 |             from: self.sender.to_owned(),
   |                               ^^^^^^^^ method cannot be called on `SubscriberEmail` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `SubscriberEmail: Clone`
           which is required by `SubscriberEmail: ToOwned`
```

The fix is as follows.

```commandline
darren@dev:~/code/zero2prod$ git diff
diff --git a/src/email_client.rs b/src/email_client.rs
index 89130ca..1f008eb 100644
--- a/src/email_client.rs
+++ b/src/email_client.rs
@@ -26,7 +26,7 @@ impl EmailClient {
     ) -> Result<(), reqwest::Error> {
         let url = format!("{}/email", self.base_url);
         let request_body = SendEmailRequest {
-            from: self.sender.to_owned(),
+            from: self.sender.as_ref().to_owned(),
             to: recipient.as_ref().to_owned(),
             subject: subject.to_owned(),
             html_body: html_content.to_owned(),
```

## Missing Import

`Request` needs to be imported at some point. Possibly on page 166 - but isn't used until page 176 so could be left to then?

```rust
  --> src/email_client.rs:69:37
   |
69 |         fn matches(&self, request: &Request) -> bool {
   |                                     ^^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
58 |     use reqwest::Request;
   |
58 |     use wiremock::Request;
   |
```

**Comment by LukeMathWalker** [comment]
Thanks a lot for the kind words on the book 😁 

On the issues you mentioned:
- `AsRef`: spot on, I fixed it. Thank you!
- Missing import: as far as I can see there is a `use wiremock::Request` in the code block on page 176 which is where we introduce the `Match` trait. Where were you getting that error?

**Comment by Darrenmeehan** [comment]
I need to double check, hit I'm pretty sure I wasn't getting the error until page 176, so adding there is perfect!

**Comment by LukeMathWalker** [comment]
Awesome, I'll close this one then 😁
