### ISSUE TITLE
Typo only

### ISSUE THREAD

**Issue by stuzenz** [LukeMathWalker/zero-to-production#88]
It is often much easier to tweak an existing setup to **suite** your specific needs than to write a new one from scratch.

Should be 'suit'

ref: https://www.lpalmieri.com/posts/2020-06-06-zero-to-production-1-setup-toolchain-ides-ci/

Just looking at your book for the first time. I love the way how you have walked through CI - it works well for the hobbiest/lone coder type like myself who is normally only exposed to CI at a superficial basis when project managing projects.

**Comment by LukeMathWalker** [comment]
Thanks for the report, fixed it 😁 
Glad you are enjoying it so far!
