### ISSUE TITLE
Chapter 3.8.5.1 - Wrong Cargo Toml 

### ISSUE THREAD

**Issue by elbart** [LukeMathWalker/zero-to-production#89]
The Cargo.toml for the SQLX features looks wrong, it seems that some contents have been somehow swallowed (especially the version).

![Screenshot 2021-04-01 at 13 29 42](https://user-images.githubusercontent.com/48974/113287819-60de8680-92ee-11eb-97e4-f846f8d8773b.png)

Suggestion for the correct one:
```
[dependencies.sqlx]
version = "0.5.1"
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
]

```

**Comment by LukeMathWalker** [comment]
I think this was raised before (and fixed) - are you looking at the latest version of the book?

**Comment by elbart** [comment]
Ahh great. My book version was not too old (something between 5th of March and mid March), however it seems to be too old already! Sorry for the duplicate!

**Comment by LukeMathWalker** [comment]
No worries at all 😁
