### ISSUE TITLE
Chapter 7.2 typo in confirmation tests.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#90]
In [Connecting the Dots](https://www.lpalmieri.com/posts/zero-downtime-deployments/#connecting-the-dots), the last line of `the_link_returned_by_subscribe_returns_a_200_if_called()` should be `    assert_eq!(response.status().as_u16(), 200);`.  `response.status` is a method, not a field.

**Comment by LukeMathWalker** [comment]
Fixed, thanks for reporting!
