### ISSUE TITLE
Chapter 7.2 typos.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#91]
1) In the example just below "We are done on POST /subscriptions, let's shift to GET /subscription/confirm:" the comment at the top with the filename should be `//! src/routes/subscriptions_confirm.rs`.

2) In the example just below "Let's pass transaction down to insert_subscriber and store_token instead of pool:" `use sqlx::Transaction` is required, but the statement isn't shown until a few examples later.

**Comment by LukeMathWalker** [comment]
Fixed both, thanks for reporting!
