### ISSUE TITLE
In 7.2 we edit the spec.yaml, but never push it to DigitalOcean.

### ISSUE THREAD

**Issue by cldershem** [LukeMathWalker/zero-to-production#92]
In Chapter 7.2 we edit the `spec.yaml` to add a environment variable, but we never update the `spec` that DigitalOcean uses. I think the chapter should mention running:

- `doctl apps list --format ID` -> returns $APP_ID
- `doctl apps update $APP_ID --spec spec.yaml`

**Comment by LukeMathWalker** [comment]
Good shout, I have added a reminder!
