### ISSUE TITLE
Typo in page 88

### ISSUE THREAD

**Issue by manuelvargastapia** [LukeMathWalker/zero-to-production#93]
Hi! There is a typo at the beginning of section 4.5.7:

> tracing_subscriber::filter::EnvLogger discards spans based on their log levels and their
origins, just as we did in env_logger via the RUST_LOG environment variable;

"tracing_subscriber::filter::EnvLogger" should be "tracing_subscriber::filter::EnvFilter", as [that's the name](https://docs.rs/tracing-subscriber/0.2.12/tracing_subscriber/struct.EnvFilter.html) of the struct.

**Comment by LukeMathWalker** [comment]
The link is right but the text is wrong 😅 Thanks for reporting!
