### ISSUE TITLE
Problem displaying content on page 105

### ISSUE THREAD

**Issue by manuelvargastapia** [LukeMathWalker/zero-to-production#94]
Hi! I found a problem at the end of page 105, section 5.3.3. Specifically, when displaying a code snippet to show how to add the `sqlx`'s `offline` feature.

PDF version:

![Screenshot from 2021-04-10 21-19-11](https://user-images.githubusercontent.com/42724299/114289160-ba0f8e00-9a43-11eb-94cb-527d6aff3278.png)

Gumroad online version:

![Screenshot from 2021-04-10 21-19-29](https://user-images.githubusercontent.com/42724299/114289165-c0056f00-9a43-11eb-93e9-9cb20bf6ad3c.png)

**Comment by LukeMathWalker** [comment]
We need to switch to the table syntax there to avoid the long line, sorry for the inconvenience.
I have updated the book, I'll release a new version shortly. Thanks for reporting!
