### ISSUE TITLE
E0277: Handler<_, _> is not implemented for `fn(Form<subscriptions::FormData>, actix_web::web::Data<Pool<Postgres>>)

### ISSUE THREAD

**Issue by maedox** [LukeMathWalker/zero-to-production#96]
I'm seeing this error every now and then. Sometimes when adding dependencies manually or just now after trying your latest release of `tracing-actix-web 0.4.0-beta.1`. I believe I first saw it after mistakenly adding `actix-web-4.0.0-beta.6` instead of `beta.3` as specified in the book. 

```rust
error[E0277]: the trait bound `fn(Form<subscriptions::FormData>, actix_web::web::Data<Pool<Postgres>>) -> impl std::future::Future {subscriptions::subscribe}: Handler<_, _>` is not satisfied
  --> src/startup.rs:15:53
   |
15 |             .route("/subscriptions", web::post().to(subscribe))
   |                                                     ^^^^^^^^^ the trait `Handler<_, _>` is not implemented for `fn(Form<subscriptions::FormData>, actix_web::web::Data<Pool<Postgres>>) -> impl std::future::Future {subscriptions::subscribe}`
```

Should be reproducible by setting `actix-web = "=4.0.0-beta.6"`  in Cargo.toml. Perhaps even without the = qualifier.
Setting `actix-web = "=4.0.0-beta.3"` makes all hell break lose, so I'm guessing it's all caused by other crates' dependencies.

I usually fix it by doing cargo clean and replacing my Cargo.lock with the one from your repository and branch for the chapter I am on. Currently `root-chapter-07`

However, I was hoping you would know if there's a way to fix it for good, and avoiding problems like these? Or even just point me in the right direction and I might be able to figure it out on my own.

PS: I'm only a few weeks old in the Rust world, and I am really enjoying the book. Outstanding work!

**Comment by LukeMathWalker** [comment]
Interesting - can you share your `Cargo.lock` file?

**Comment by briandiephuis** [comment]
I have the same issue; this is my `Cargo.lock` (`.txt` added by me because Github doesn't seem to allow `.lock` file uploads)
[Cargo.lock.txt](https://github.com/LukeMathWalker/zero-to-production/files/6376719/Cargo.lock.txt)

**Comment by maedox** [comment]
I reproduced it on the main branch like this:

1. update `tracing-actix-web` to `0.4.0-beta.1`
2. cargo check => errors.
3. cargo clean
4. undo the version change from point 1
5. cargo check => errors.

Cargo.lock is updated and keeps causing issues.

[Cargo.lock.txt](https://github.com/LukeMathWalker/zero-to-production/files/6376896/Cargo.lock.txt)

**Comment by LukeMathWalker** [comment]
Have you tried running `cargo update` after step `2`? Do you get the same errors afterwards?

**Comment by maedox** [comment]
Tried it and it did a bunch of changes. Same errors, though.
Here's the lock file afterwards: 
[Cargo.lock.txt](https://github.com/LukeMathWalker/zero-to-production/files/6377011/Cargo.lock.txt)

**Comment by briandiephuis** [comment]
Seems like they rushed beta.6 and broke the error types (see: https://github.com/actix/actix-web/issues/2173).

Pinning `actix-http`, `actix-service` and `actix-web` :
```
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
actix-web = "=4.0.0-beta.5"
```
As suggested in (https://github.com/actix/actix-web/issues/2185)

And running `cargo clean && cargo update && cargo check` fixed it for me :)

**Comment by maedox** [comment]
Woops. 😬
Great detective work. Worked very well, thank you.

**Comment by skovmand** [comment]
Thank you for reporting :+1:. This was a really strange error message, glad I found help here. Spent an hour on this one before I found this issue.

**Comment by gyzerok** [comment]
Had the same issue and fixed it in the following way:

```rust
pub async fn subscriptions(form: web::Form<FormData>, db_pool: web::Data<PgPool>) -> HttpResponse {
    let query = sqlx::query!(...)

    match query {
        Ok(_) => HttpResponse::Ok().finish(),
        Err(e) => {
            eprintln!("Faield to execute query: {}", e);
            HttpResponse::InternalServerError().finish()
        }
    }
}
```

For me it makes a little bit more sense than the way described in the book since `HttpResponse` type seems already to be sort of `Result` (it can contain successes and failures). Wrapping it one more time feels weird. Hope this feedback helps :)

**Comment by LukeMathWalker** [comment]
Solved in the next release, going out tomorrow 😁 
Required a _significant_ rework of many chapters 😅
