### ISSUE TITLE
Nit: Dockerfile lint

### ISSUE THREAD

**Issue by chaosteil** [LukeMathWalker/zero-to-production#99]
My linter keeps screaming at me that all the `WORKDIR` paths should be absolute, not relative for better readability, i.e.:
```
WORKDIR /app
```
for example: https://github.com/LukeMathWalker/zero-to-production/blob/7f71a5c815a89c36a569d58b63a41ef787831260/Dockerfile#L2

---

sidenote: I absolutely adore the thoroughness and everything throughout the book, thanks for writing it!

**Comment by LukeMathWalker** [comment]
Solved in the next release, going out tomorrow 😁
